/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { responsesCreateResponse } from "../funcs/responsesCreateResponse.js";
import { responsesCreateStreamingResponse } from "../funcs/responsesCreateStreamingResponse.js";
import { EventStream } from "../lib/event-streams.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Responses extends ClientSDK {
  /**
   * *[OpenAI Only]* Responses API: Create a model response for the given input
   */
  async createResponse(
    request: models.ResponsesRequest,
    options?: RequestOptions,
  ): Promise<models.ResponseT> {
    return unwrapAsync(responsesCreateResponse(
      this,
      request,
      options,
    ));
  }

  /**
   * *[OpenAI Only]* Responses API: Create a streaming model response for the given input using server-sent events.
   */
  async createStreamingResponse(
    request: models.ResponsesRequestStream,
    options?: RequestOptions,
  ): Promise<EventStream<models.ResponseEvent>> {
    return unwrapAsync(responsesCreateStreamingResponse(
      this,
      request,
      options,
    ));
  }
}
