/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Router } from "./router.js";
import { System } from "./system.js";

export class Sudo extends ClientSDK {
  private _system?: System;
  get system(): System {
    return (this._system ??= new System(this._options));
  }

  private _router?: Router;
  get router(): Router {
    return (this._router ??= new Router(this._options));
  }
}
