/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { systemGetSupportedModels } from "../funcs/systemGetSupportedModels.js";
import { systemHealthCheck } from "../funcs/systemHealthCheck.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class System extends ClientSDK {
  /**
   * Check if the Sudo API and backend infrastructure are health and ready to accept connections.
   */
  async healthCheck(
    options?: RequestOptions,
  ): Promise<any> {
    return unwrapAsync(systemHealthCheck(
      this,
      options,
    ));
  }

  /**
   * Get a list of all AI models supported in the Sudo API.
   */
  async getSupportedModels(
    options?: RequestOptions,
  ): Promise<models.SupportedModelsList> {
    return unwrapAsync(systemGetSupportedModels(
      this,
      options,
    ));
  }
}
