/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the sudo SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx systemHealthCheck.ts
 */

import { Sudo } from "sudo";

const sudo = new Sudo({
  serverURL: "https://api.example.com",
  apiKey: process.env["SUDO_API_KEY"] ?? "",
});

async function main() {
  const result = await sudo.healthCheck();

  console.log(result);
}

main().catch(console.error);
