/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type DeleteChatCompletionRequest = {
  /**
   * ID of the chat completion
   */
  completionId: string;
};

/** @internal */
export type DeleteChatCompletionRequest$Outbound = {
  completion_id: string;
};

/** @internal */
export const DeleteChatCompletionRequest$outboundSchema: z.ZodType<
  DeleteChatCompletionRequest$Outbound,
  z.ZodTypeDef,
  DeleteChatCompletionRequest
> = z.object({
  completionId: z.string(),
}).transform((v) => {
  return remap$(v, {
    completionId: "completion_id",
  });
});

export function deleteChatCompletionRequestToJSON(
  deleteChatCompletionRequest: DeleteChatCompletionRequest,
): string {
  return JSON.stringify(
    DeleteChatCompletionRequest$outboundSchema.parse(
      deleteChatCompletionRequest,
    ),
  );
}
