/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetChatCompletionRequest = {
  /**
   * ID of the chat completion
   */
  completionId: string;
};

/** @internal */
export type GetChatCompletionRequest$Outbound = {
  completion_id: string;
};

/** @internal */
export const GetChatCompletionRequest$outboundSchema: z.ZodType<
  GetChatCompletionRequest$Outbound,
  z.ZodTypeDef,
  GetChatCompletionRequest
> = z.object({
  completionId: z.string(),
}).transform((v) => {
  return remap$(v, {
    completionId: "completion_id",
  });
});

export function getChatCompletionRequestToJSON(
  getChatCompletionRequest: GetChatCompletionRequest,
): string {
  return JSON.stringify(
    GetChatCompletionRequest$outboundSchema.parse(getChatCompletionRequest),
  );
}
