/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetChatCompletionMessagesRequest = {
  /**
   * ID of the chat completion
   */
  completionId: string;
  /**
   * Identifier for the last message from the previous pagination request.
   */
  after?: string | undefined;
  /**
   * Number of messages to retrieve.
   */
  limit?: number | undefined;
  /**
   * Sort order for messages by timestamp. Use asc for ascending order or desc for descending order. Defaults to asc.
   */
  order?: string | undefined;
};

/** @internal */
export const GetChatCompletionMessagesRequest$inboundSchema: z.ZodType<
  GetChatCompletionMessagesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  completion_id: z.string(),
  after: z.string().optional(),
  limit: z.number().int().optional(),
  order: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "completion_id": "completionId",
  });
});

/** @internal */
export type GetChatCompletionMessagesRequest$Outbound = {
  completion_id: string;
  after?: string | undefined;
  limit?: number | undefined;
  order?: string | undefined;
};

/** @internal */
export const GetChatCompletionMessagesRequest$outboundSchema: z.ZodType<
  GetChatCompletionMessagesRequest$Outbound,
  z.ZodTypeDef,
  GetChatCompletionMessagesRequest
> = z.object({
  completionId: z.string(),
  after: z.string().optional(),
  limit: z.number().int().optional(),
  order: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    completionId: "completion_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetChatCompletionMessagesRequest$ {
  /** @deprecated use `GetChatCompletionMessagesRequest$inboundSchema` instead. */
  export const inboundSchema = GetChatCompletionMessagesRequest$inboundSchema;
  /** @deprecated use `GetChatCompletionMessagesRequest$outboundSchema` instead. */
  export const outboundSchema = GetChatCompletionMessagesRequest$outboundSchema;
  /** @deprecated use `GetChatCompletionMessagesRequest$Outbound` instead. */
  export type Outbound = GetChatCompletionMessagesRequest$Outbound;
}

export function getChatCompletionMessagesRequestToJSON(
  getChatCompletionMessagesRequest: GetChatCompletionMessagesRequest,
): string {
  return JSON.stringify(
    GetChatCompletionMessagesRequest$outboundSchema.parse(
      getChatCompletionMessagesRequest,
    ),
  );
}

export function getChatCompletionMessagesRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetChatCompletionMessagesRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetChatCompletionMessagesRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetChatCompletionMessagesRequest' from JSON`,
  );
}
