/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetChatCompletionMessagesRequest = {
  /**
   * ID of the chat completion
   */
  completionId: string;
  /**
   * Identifier for the last message from the previous pagination request.
   */
  after?: string | undefined;
  /**
   * Number of messages to retrieve.
   */
  limit?: number | undefined;
  /**
   * Sort order for messages by timestamp. Use asc for ascending order or desc for descending order. Defaults to asc.
   */
  order?: string | undefined;
};

/** @internal */
export type GetChatCompletionMessagesRequest$Outbound = {
  completion_id: string;
  after?: string | undefined;
  limit?: number | undefined;
  order?: string | undefined;
};

/** @internal */
export const GetChatCompletionMessagesRequest$outboundSchema: z.ZodType<
  GetChatCompletionMessagesRequest$Outbound,
  z.ZodTypeDef,
  GetChatCompletionMessagesRequest
> = z.object({
  completionId: z.string(),
  after: z.string().optional(),
  limit: z.number().int().optional(),
  order: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    completionId: "completion_id",
  });
});

export function getChatCompletionMessagesRequestToJSON(
  getChatCompletionMessagesRequest: GetChatCompletionMessagesRequest,
): string {
  return JSON.stringify(
    GetChatCompletionMessagesRequest$outboundSchema.parse(
      getChatCompletionMessagesRequest,
    ),
  );
}
