/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type ListChatCompletionsRequest = {
  /**
   * Identifier for the last chat completion from the previous pagination request.
   */
  after?: string | undefined;
  /**
   * Number of Chat Completions to retrieve.
   */
  limit?: number | undefined;
  /**
   * A list of metadata keys to filter the Chat Completions by. Example: metadata[key1]=value1&metadata[key2]=value2
   */
  metadata?: { [k: string]: string } | undefined;
  /**
   * The model used to generate the Chat Completions.
   */
  model?: string | undefined;
  /**
   * Sort order for Chat Completions by timestamp. Use asc for ascending order or desc for descending order. Defaults to asc.
   */
  order?: string | undefined;
};

/** @internal */
export type ListChatCompletionsRequest$Outbound = {
  after?: string | undefined;
  limit?: number | undefined;
  metadata?: { [k: string]: string } | undefined;
  model?: string | undefined;
  order?: string | undefined;
};

/** @internal */
export const ListChatCompletionsRequest$outboundSchema: z.ZodType<
  ListChatCompletionsRequest$Outbound,
  z.ZodTypeDef,
  ListChatCompletionsRequest
> = z.object({
  after: z.string().optional(),
  limit: z.number().int().optional(),
  metadata: z.record(z.string()).optional(),
  model: z.string().optional(),
  order: z.string().optional(),
});

export function listChatCompletionsRequestToJSON(
  listChatCompletionsRequest: ListChatCompletionsRequest,
): string {
  return JSON.stringify(
    ListChatCompletionsRequest$outboundSchema.parse(listChatCompletionsRequest),
  );
}
