/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

/**
 * Set of 16 key-value pairs that can be attached to an object. This can be useful for storing additional information about the object in a structured format, and querying for objects via API or the dashboard. Keys are strings with a maximum length of 64 characters. Values are strings with a maximum length of 512 characters.
 */
export type UpdateChatCompletionRequestBody = {
  /**
   * The metadata key-value pairs to attach to the completion.
   */
  metadata: { [k: string]: string };
};

export type UpdateChatCompletionRequest = {
  /**
   * ID of the chat completion
   */
  completionId: string;
  /**
   * Set of 16 key-value pairs that can be attached to an object. This can be useful for storing additional information about the object in a structured format, and querying for objects via API or the dashboard. Keys are strings with a maximum length of 64 characters. Values are strings with a maximum length of 512 characters.
   */
  requestBody: UpdateChatCompletionRequestBody;
};

/** @internal */
export type UpdateChatCompletionRequestBody$Outbound = {
  metadata: { [k: string]: string };
};

/** @internal */
export const UpdateChatCompletionRequestBody$outboundSchema: z.ZodType<
  UpdateChatCompletionRequestBody$Outbound,
  z.ZodTypeDef,
  UpdateChatCompletionRequestBody
> = z.object({
  metadata: z.record(z.string()),
});

export function updateChatCompletionRequestBodyToJSON(
  updateChatCompletionRequestBody: UpdateChatCompletionRequestBody,
): string {
  return JSON.stringify(
    UpdateChatCompletionRequestBody$outboundSchema.parse(
      updateChatCompletionRequestBody,
    ),
  );
}

/** @internal */
export type UpdateChatCompletionRequest$Outbound = {
  completion_id: string;
  RequestBody: UpdateChatCompletionRequestBody$Outbound;
};

/** @internal */
export const UpdateChatCompletionRequest$outboundSchema: z.ZodType<
  UpdateChatCompletionRequest$Outbound,
  z.ZodTypeDef,
  UpdateChatCompletionRequest
> = z.object({
  completionId: z.string(),
  requestBody: z.lazy(() => UpdateChatCompletionRequestBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    completionId: "completion_id",
    requestBody: "RequestBody",
  });
});

export function updateChatCompletionRequestToJSON(
  updateChatCompletionRequest: UpdateChatCompletionRequest,
): string {
  return JSON.stringify(
    UpdateChatCompletionRequest$outboundSchema.parse(
      updateChatCompletionRequest,
    ),
  );
}
