/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { ClosedEnum } from "../types/enums.js";
import {
  ChatMessage,
  ChatMessage$Outbound,
  ChatMessage$outboundSchema,
} from "./chatmessage.js";
import { Tool, Tool$Outbound, Tool$outboundSchema } from "./tool.js";

/**
 * Specifies the output audio format. Must be one of wav, mp3, flac, opus, or pcm16.
 */
export const ChatCompletionRequestStreamFormat = {
  Wav: "wav",
  Mp3: "mp3",
  Flac: "flac",
  Opus: "opus",
  Pcm16: "pcm16",
} as const;
/**
 * Specifies the output audio format. Must be one of wav, mp3, flac, opus, or pcm16.
 */
export type ChatCompletionRequestStreamFormat = ClosedEnum<
  typeof ChatCompletionRequestStreamFormat
>;

/**
 * Specifies the voice type. Supported voices are alloy, echo, fable, onyx, nova, and shimmer.
 */
export const ChatCompletionRequestStreamVoice = {
  Alloy: "alloy",
  Echo: "echo",
  Fable: "fable",
  Onyx: "onyx",
  Nova: "nova",
  Shimmer: "shimmer",
} as const;
/**
 * Specifies the voice type. Supported voices are alloy, echo, fable, onyx, nova, and shimmer.
 */
export type ChatCompletionRequestStreamVoice = ClosedEnum<
  typeof ChatCompletionRequestStreamVoice
>;

/**
 * Parameters for audio output. Required when audio output is requested with modalities: ["audio"].
 */
export type ChatCompletionRequestStreamAudio = {
  /**
   * Specifies the output audio format. Must be one of wav, mp3, flac, opus, or pcm16.
   */
  format?: ChatCompletionRequestStreamFormat | undefined;
  /**
   * Specifies the voice type. Supported voices are alloy, echo, fable, onyx, nova, and shimmer.
   */
  voice?: ChatCompletionRequestStreamVoice | undefined;
};

export const ChatCompletionRequestStreamModality = {
  Text: "text",
  Audio: "audio",
} as const;
export type ChatCompletionRequestStreamModality = ClosedEnum<
  typeof ChatCompletionRequestStreamModality
>;

export const ChatCompletionRequestStreamTypeContent = {
  Content: "content",
} as const;
export type ChatCompletionRequestStreamTypeContent = ClosedEnum<
  typeof ChatCompletionRequestStreamTypeContent
>;

/**
 * Configuration for a Predicted Output, which can greatly improve response times when large parts of the model response are known ahead of time. This is most common when you are regenerating a file with only minor changes to most of the content.
 */
export type ChatCompletionRequestStreamPrediction = {
  type?: ChatCompletionRequestStreamTypeContent | undefined;
  /**
   * The predicted content for the completion.
   */
  content?: string | undefined;
};

/**
 * o1 models only. Constrains effort on reasoning for reasoning models. Currently supported values are low, medium, and high. Reducing reasoning effort can result in faster responses and fewer tokens used on reasoning in a response.
 */
export const ChatCompletionRequestStreamReasoningEffort = {
  Low: "low",
  Medium: "medium",
  High: "high",
} as const;
/**
 * o1 models only. Constrains effort on reasoning for reasoning models. Currently supported values are low, medium, and high. Reducing reasoning effort can result in faster responses and fewer tokens used on reasoning in a response.
 */
export type ChatCompletionRequestStreamReasoningEffort = ClosedEnum<
  typeof ChatCompletionRequestStreamReasoningEffort
>;

export const ChatCompletionRequestStreamTypeJSONSchema = {
  JsonSchema: "json_schema",
} as const;
export type ChatCompletionRequestStreamTypeJSONSchema = ClosedEnum<
  typeof ChatCompletionRequestStreamTypeJSONSchema
>;

/**
 * The JSON schema definition for structured outputs.
 */
export type ChatCompletionRequestStreamJsonSchema = {
  /**
   * The name of the response format. Must be a-z, A-Z, 0-9, or contain underscores and dashes, with a maximum length of 64.
   */
  name: string;
  /**
   * A description of what the response format is for, used by the model to determine how to respond in the format.
   */
  description?: string | undefined;
  /**
   * The schema for the response format, described as a JSON Schema object.
   */
  schema: { [k: string]: any };
  /**
   * Whether to enable strict schema adherence when generating the output.
   */
  strict?: boolean | undefined;
};

export type ChatCompletionRequestStreamResponseFormatJSONSchema = {
  type: ChatCompletionRequestStreamTypeJSONSchema;
  /**
   * The JSON schema definition for structured outputs.
   */
  jsonSchema: ChatCompletionRequestStreamJsonSchema;
};

export const ChatCompletionRequestStreamTypeJSONObject = {
  JsonObject: "json_object",
} as const;
export type ChatCompletionRequestStreamTypeJSONObject = ClosedEnum<
  typeof ChatCompletionRequestStreamTypeJSONObject
>;

export type ChatCompletionRequestStreamResponseFormatJSONObject = {
  type: ChatCompletionRequestStreamTypeJSONObject;
};

export const ChatCompletionRequestStreamTypeText = {
  Text: "text",
} as const;
export type ChatCompletionRequestStreamTypeText = ClosedEnum<
  typeof ChatCompletionRequestStreamTypeText
>;

export type ChatCompletionRequestStreamResponseFormatText = {
  type: ChatCompletionRequestStreamTypeText;
};

/**
 * An object specifying the format that the model must output. Compatible with GPT-4o, GPT-4o mini, GPT-4 Turbo and all GPT-3.5 Turbo models newer than gpt-3.5-turbo-1106. Setting to { "type": "json_schema", "json_schema": {...} } enables Structured Outputs which guarantee the model will match your supplied JSON schema. Setting to { "type": "json_object" } enables JSON mode, which guarantees the message the model generates is valid JSON.
 */
export type ChatCompletionRequestStreamResponseFormatUnion =
  | ChatCompletionRequestStreamResponseFormatJSONSchema
  | ChatCompletionRequestStreamResponseFormatText
  | ChatCompletionRequestStreamResponseFormatJSONObject;

/**
 * Specifies the latency tier to use for processing the request. This parameter is relevant for customers subscribed to the scale tier service.
 */
export const ChatCompletionRequestStreamServiceTier = {
  Auto: "auto",
  Default: "default",
} as const;
/**
 * Specifies the latency tier to use for processing the request. This parameter is relevant for customers subscribed to the scale tier service.
 */
export type ChatCompletionRequestStreamServiceTier = ClosedEnum<
  typeof ChatCompletionRequestStreamServiceTier
>;

/**
 * Options for streaming response. Only set this when you set stream: true.
 */
export type ChatCompletionRequestStreamStreamOptions = {
  /**
   * If set, an additional chunk will be streamed before the data: [DONE] message. The usage field on this chunk shows the token usage statistics for the entire request, and the choices field will always be an empty array. All other chunks will also include a usage field, but with a null value.
   */
  includeUsage?: boolean | undefined;
};

export const ChatCompletionRequestStreamToolChoiceType = {
  Function: "function",
} as const;
export type ChatCompletionRequestStreamToolChoiceType = ClosedEnum<
  typeof ChatCompletionRequestStreamToolChoiceType
>;

export type ChatCompletionRequestStreamFunction = {
  name: string;
};

export type ChatCompletionRequestStreamToolChoiceFunction = {
  type: ChatCompletionRequestStreamToolChoiceType;
  function: ChatCompletionRequestStreamFunction;
};

export const ChatCompletionRequestStreamToolChoiceEnum = {
  None: "none",
  Auto: "auto",
  Required: "required",
} as const;
export type ChatCompletionRequestStreamToolChoiceEnum = ClosedEnum<
  typeof ChatCompletionRequestStreamToolChoiceEnum
>;

/**
 * Controls which (if any) tool is called by the model. none means the model won't call any tool and instead generates a message. auto means the model can pick between generating a message or calling one or more tools. required means the model must call one or more tools. Specifying a particular tool via {"type": "function", "function": {"name": "my_function"}} forces the model to call that tool. none is the default when no tools are present. auto is the default if tools are present.
 */
export type ChatCompletionRequestStreamToolChoiceUnion =
  | ChatCompletionRequestStreamToolChoiceFunction
  | ChatCompletionRequestStreamToolChoiceEnum;

export type ChatCompletionRequestStream = {
  /**
   * Parameters for audio output. Required when audio output is requested with modalities: ["audio"].
   */
  audio?: ChatCompletionRequestStreamAudio | null | undefined;
  /**
   * Number between -2.0 and 2.0. Positive values penalize new tokens based on their existing frequency in the text so far, decreasing the model's likelihood to repeat the same line verbatim.
   */
  frequencyPenalty?: number | null | undefined;
  /**
   * Modify the likelihood of specified tokens appearing in the completion. Accepts a JSON object that maps tokens (specified by their token ID in the tokenizer) to an associated bias value from -100 to 100. Mathematically, the bias is added to the logits generated by the model prior to sampling. The exact effect will vary per model, but values between -1 and 1 should decrease or increase likelihood of selection; values like -100 or 100 should result in a ban or exclusive selection of the relevant token.
   */
  logitBias?: { [k: string]: number } | null | undefined;
  /**
   * Whether to return log probabilities of the output tokens or not. If true, returns the log probabilities of each output token returned in the content of message.
   */
  logprobs?: boolean | null | undefined;
  /**
   * An upper bound for the number of tokens that can be generated for a completion, including visible output tokens and reasoning tokens.
   */
  maxCompletionTokens?: number | null | undefined;
  /**
   * A list of messages comprising the conversation so far. Depending on the model you use, different message types (modalities) are supported, like text, images, and audio.
   */
  messages: Array<ChatMessage>;
  /**
   * Developer-defined tags and values used for filtering completions in the stored completions dashboard.
   */
  metadata?: { [k: string]: string } | null | undefined;
  /**
   * Output types that you would like the model to generate for this request. Most models are capable of generating text, which is the default: ["text"]. The gpt-4o-audio-preview model can also be used to generate audio. To request that this model generate both text and audio responses, you can use: ["text", "audio"].
   */
  modalities?: Array<ChatCompletionRequestStreamModality> | null | undefined;
  /**
   * Model name used to generate the response, like gpt-4o or deepseek-reasoner. Sudo offers a wide range of models with different capabilities, performance characteristics, and price points. Refer to the [docs](https://docs.sudoapp.dev/overview/models) to browse and compare available models.
   */
  model: string;
  /**
   * How many chat completion choices to generate for each input message. Note that you will be charged based on the number of generated tokens across all of the choices. Keep n as 1 to minimize costs.
   */
  n?: number | null | undefined;
  /**
   * Whether to enable parallel function calling during tool use.
   */
  parallelToolCalls?: boolean | null | undefined;
  /**
   * Configuration for a Predicted Output, which can greatly improve response times when large parts of the model response are known ahead of time. This is most common when you are regenerating a file with only minor changes to most of the content.
   */
  prediction?: ChatCompletionRequestStreamPrediction | null | undefined;
  /**
   * Number between -2.0 and 2.0. Positive values penalize new tokens based on whether they appear in the text so far, increasing the model's likelihood to talk about new topics.
   */
  presencePenalty?: number | null | undefined;
  /**
   * A unique identifier for caching prompts to improve response times for repeated requests.
   */
  promptCacheKey?: string | null | undefined;
  /**
   * o1 models only. Constrains effort on reasoning for reasoning models. Currently supported values are low, medium, and high. Reducing reasoning effort can result in faster responses and fewer tokens used on reasoning in a response.
   */
  reasoningEffort?:
    | ChatCompletionRequestStreamReasoningEffort
    | null
    | undefined;
  /**
   * An object specifying the format that the model must output. Compatible with GPT-4o, GPT-4o mini, GPT-4 Turbo and all GPT-3.5 Turbo models newer than gpt-3.5-turbo-1106. Setting to { "type": "json_schema", "json_schema": {...} } enables Structured Outputs which guarantee the model will match your supplied JSON schema. Setting to { "type": "json_object" } enables JSON mode, which guarantees the message the model generates is valid JSON.
   */
  responseFormat?:
    | ChatCompletionRequestStreamResponseFormatJSONSchema
    | ChatCompletionRequestStreamResponseFormatText
    | ChatCompletionRequestStreamResponseFormatJSONObject
    | null
    | undefined;
  /**
   * If specified, our system will make a best effort to sample deterministically, such that repeated requests with the same seed and parameters should return the same result. Determinism isn't guaranteed, and you should refer to the system_fingerprint response parameter to monitor changes in the backend.
   */
  seed?: number | null | undefined;
  /**
   * Specifies the latency tier to use for processing the request. This parameter is relevant for customers subscribed to the scale tier service.
   */
  serviceTier?: ChatCompletionRequestStreamServiceTier | null | undefined;
  /**
   * Not supported with latest reasoning models o3 and o4-mini. Up to 4 sequences where the API will stop generating further tokens. The returned text will not contain the stop sequence.
   */
  stop?: Array<string> | null | undefined;
  /**
   * Whether or not to store the output of this chat completion request for use in our model distillation or evaluation products.
   */
  store?: boolean | null | undefined;
  /**
   * If set, partial message deltas will be sent as server-sent events. For streaming responses, this must be true.
   */
  stream?: boolean | undefined;
  /**
   * Options for streaming response. Only set this when you set stream: true.
   */
  streamOptions?: ChatCompletionRequestStreamStreamOptions | null | undefined;
  /**
   * What sampling temperature to use, between 0 and 2. Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic. We generally recommend altering this or top_p but not both.
   */
  temperature?: number | null | undefined;
  /**
   * Controls which (if any) tool is called by the model. none means the model won't call any tool and instead generates a message. auto means the model can pick between generating a message or calling one or more tools. required means the model must call one or more tools. Specifying a particular tool via {"type": "function", "function": {"name": "my_function"}} forces the model to call that tool. none is the default when no tools are present. auto is the default if tools are present.
   */
  toolChoice?:
    | ChatCompletionRequestStreamToolChoiceFunction
    | ChatCompletionRequestStreamToolChoiceEnum
    | null
    | undefined;
  /**
   * A list of tools the model may call. Currently, only functions are supported as a tool. Use this to provide a list of functions the model may generate JSON inputs for. A max of 128 functions are supported.
   */
  tools?: Array<Tool> | null | undefined;
  /**
   * An integer between 0 and 20 specifying the number of most likely tokens to return at each token position, each with an associated log probability. logprobs must be set to true if this parameter is used.
   */
  topLogprobs?: number | null | undefined;
  /**
   * An alternative to sampling with temperature, called nucleus sampling, where the model considers the results of the tokens with top_p probability mass. So 0.1 means only the tokens comprising the top 10% probability mass are considered. We generally recommend altering this or temperature but not both.
   */
  topP?: number | null | undefined;
  /**
   * A unique identifier representing your end-user, which can help to monitor and detect abuse.
   */
  user?: string | null | undefined;
};

/** @internal */
export const ChatCompletionRequestStreamFormat$outboundSchema: z.ZodNativeEnum<
  typeof ChatCompletionRequestStreamFormat
> = z.nativeEnum(ChatCompletionRequestStreamFormat);

/** @internal */
export const ChatCompletionRequestStreamVoice$outboundSchema: z.ZodNativeEnum<
  typeof ChatCompletionRequestStreamVoice
> = z.nativeEnum(ChatCompletionRequestStreamVoice);

/** @internal */
export type ChatCompletionRequestStreamAudio$Outbound = {
  format?: string | undefined;
  voice?: string | undefined;
};

/** @internal */
export const ChatCompletionRequestStreamAudio$outboundSchema: z.ZodType<
  ChatCompletionRequestStreamAudio$Outbound,
  z.ZodTypeDef,
  ChatCompletionRequestStreamAudio
> = z.object({
  format: ChatCompletionRequestStreamFormat$outboundSchema.optional(),
  voice: ChatCompletionRequestStreamVoice$outboundSchema.optional(),
});

export function chatCompletionRequestStreamAudioToJSON(
  chatCompletionRequestStreamAudio: ChatCompletionRequestStreamAudio,
): string {
  return JSON.stringify(
    ChatCompletionRequestStreamAudio$outboundSchema.parse(
      chatCompletionRequestStreamAudio,
    ),
  );
}

/** @internal */
export const ChatCompletionRequestStreamModality$outboundSchema:
  z.ZodNativeEnum<typeof ChatCompletionRequestStreamModality> = z.nativeEnum(
    ChatCompletionRequestStreamModality,
  );

/** @internal */
export const ChatCompletionRequestStreamTypeContent$outboundSchema:
  z.ZodNativeEnum<typeof ChatCompletionRequestStreamTypeContent> = z.nativeEnum(
    ChatCompletionRequestStreamTypeContent,
  );

/** @internal */
export type ChatCompletionRequestStreamPrediction$Outbound = {
  type?: string | undefined;
  content?: string | undefined;
};

/** @internal */
export const ChatCompletionRequestStreamPrediction$outboundSchema: z.ZodType<
  ChatCompletionRequestStreamPrediction$Outbound,
  z.ZodTypeDef,
  ChatCompletionRequestStreamPrediction
> = z.object({
  type: ChatCompletionRequestStreamTypeContent$outboundSchema.optional(),
  content: z.string().optional(),
});

export function chatCompletionRequestStreamPredictionToJSON(
  chatCompletionRequestStreamPrediction: ChatCompletionRequestStreamPrediction,
): string {
  return JSON.stringify(
    ChatCompletionRequestStreamPrediction$outboundSchema.parse(
      chatCompletionRequestStreamPrediction,
    ),
  );
}

/** @internal */
export const ChatCompletionRequestStreamReasoningEffort$outboundSchema:
  z.ZodNativeEnum<typeof ChatCompletionRequestStreamReasoningEffort> = z
    .nativeEnum(ChatCompletionRequestStreamReasoningEffort);

/** @internal */
export const ChatCompletionRequestStreamTypeJSONSchema$outboundSchema:
  z.ZodNativeEnum<typeof ChatCompletionRequestStreamTypeJSONSchema> = z
    .nativeEnum(ChatCompletionRequestStreamTypeJSONSchema);

/** @internal */
export type ChatCompletionRequestStreamJsonSchema$Outbound = {
  name: string;
  description?: string | undefined;
  schema: { [k: string]: any };
  strict?: boolean | undefined;
};

/** @internal */
export const ChatCompletionRequestStreamJsonSchema$outboundSchema: z.ZodType<
  ChatCompletionRequestStreamJsonSchema$Outbound,
  z.ZodTypeDef,
  ChatCompletionRequestStreamJsonSchema
> = z.object({
  name: z.string(),
  description: z.string().optional(),
  schema: z.record(z.any()),
  strict: z.boolean().optional(),
});

export function chatCompletionRequestStreamJsonSchemaToJSON(
  chatCompletionRequestStreamJsonSchema: ChatCompletionRequestStreamJsonSchema,
): string {
  return JSON.stringify(
    ChatCompletionRequestStreamJsonSchema$outboundSchema.parse(
      chatCompletionRequestStreamJsonSchema,
    ),
  );
}

/** @internal */
export type ChatCompletionRequestStreamResponseFormatJSONSchema$Outbound = {
  type: string;
  json_schema: ChatCompletionRequestStreamJsonSchema$Outbound;
};

/** @internal */
export const ChatCompletionRequestStreamResponseFormatJSONSchema$outboundSchema:
  z.ZodType<
    ChatCompletionRequestStreamResponseFormatJSONSchema$Outbound,
    z.ZodTypeDef,
    ChatCompletionRequestStreamResponseFormatJSONSchema
  > = z.object({
    type: ChatCompletionRequestStreamTypeJSONSchema$outboundSchema,
    jsonSchema: z.lazy(() =>
      ChatCompletionRequestStreamJsonSchema$outboundSchema
    ),
  }).transform((v) => {
    return remap$(v, {
      jsonSchema: "json_schema",
    });
  });

export function chatCompletionRequestStreamResponseFormatJSONSchemaToJSON(
  chatCompletionRequestStreamResponseFormatJSONSchema:
    ChatCompletionRequestStreamResponseFormatJSONSchema,
): string {
  return JSON.stringify(
    ChatCompletionRequestStreamResponseFormatJSONSchema$outboundSchema.parse(
      chatCompletionRequestStreamResponseFormatJSONSchema,
    ),
  );
}

/** @internal */
export const ChatCompletionRequestStreamTypeJSONObject$outboundSchema:
  z.ZodNativeEnum<typeof ChatCompletionRequestStreamTypeJSONObject> = z
    .nativeEnum(ChatCompletionRequestStreamTypeJSONObject);

/** @internal */
export type ChatCompletionRequestStreamResponseFormatJSONObject$Outbound = {
  type: string;
};

/** @internal */
export const ChatCompletionRequestStreamResponseFormatJSONObject$outboundSchema:
  z.ZodType<
    ChatCompletionRequestStreamResponseFormatJSONObject$Outbound,
    z.ZodTypeDef,
    ChatCompletionRequestStreamResponseFormatJSONObject
  > = z.object({
    type: ChatCompletionRequestStreamTypeJSONObject$outboundSchema,
  });

export function chatCompletionRequestStreamResponseFormatJSONObjectToJSON(
  chatCompletionRequestStreamResponseFormatJSONObject:
    ChatCompletionRequestStreamResponseFormatJSONObject,
): string {
  return JSON.stringify(
    ChatCompletionRequestStreamResponseFormatJSONObject$outboundSchema.parse(
      chatCompletionRequestStreamResponseFormatJSONObject,
    ),
  );
}

/** @internal */
export const ChatCompletionRequestStreamTypeText$outboundSchema:
  z.ZodNativeEnum<typeof ChatCompletionRequestStreamTypeText> = z.nativeEnum(
    ChatCompletionRequestStreamTypeText,
  );

/** @internal */
export type ChatCompletionRequestStreamResponseFormatText$Outbound = {
  type: string;
};

/** @internal */
export const ChatCompletionRequestStreamResponseFormatText$outboundSchema:
  z.ZodType<
    ChatCompletionRequestStreamResponseFormatText$Outbound,
    z.ZodTypeDef,
    ChatCompletionRequestStreamResponseFormatText
  > = z.object({
    type: ChatCompletionRequestStreamTypeText$outboundSchema,
  });

export function chatCompletionRequestStreamResponseFormatTextToJSON(
  chatCompletionRequestStreamResponseFormatText:
    ChatCompletionRequestStreamResponseFormatText,
): string {
  return JSON.stringify(
    ChatCompletionRequestStreamResponseFormatText$outboundSchema.parse(
      chatCompletionRequestStreamResponseFormatText,
    ),
  );
}

/** @internal */
export type ChatCompletionRequestStreamResponseFormatUnion$Outbound =
  | ChatCompletionRequestStreamResponseFormatJSONSchema$Outbound
  | ChatCompletionRequestStreamResponseFormatText$Outbound
  | ChatCompletionRequestStreamResponseFormatJSONObject$Outbound;

/** @internal */
export const ChatCompletionRequestStreamResponseFormatUnion$outboundSchema:
  z.ZodType<
    ChatCompletionRequestStreamResponseFormatUnion$Outbound,
    z.ZodTypeDef,
    ChatCompletionRequestStreamResponseFormatUnion
  > = z.union([
    z.lazy(() =>
      ChatCompletionRequestStreamResponseFormatJSONSchema$outboundSchema
    ),
    z.lazy(() => ChatCompletionRequestStreamResponseFormatText$outboundSchema),
    z.lazy(() =>
      ChatCompletionRequestStreamResponseFormatJSONObject$outboundSchema
    ),
  ]);

export function chatCompletionRequestStreamResponseFormatUnionToJSON(
  chatCompletionRequestStreamResponseFormatUnion:
    ChatCompletionRequestStreamResponseFormatUnion,
): string {
  return JSON.stringify(
    ChatCompletionRequestStreamResponseFormatUnion$outboundSchema.parse(
      chatCompletionRequestStreamResponseFormatUnion,
    ),
  );
}

/** @internal */
export const ChatCompletionRequestStreamServiceTier$outboundSchema:
  z.ZodNativeEnum<typeof ChatCompletionRequestStreamServiceTier> = z.nativeEnum(
    ChatCompletionRequestStreamServiceTier,
  );

/** @internal */
export type ChatCompletionRequestStreamStreamOptions$Outbound = {
  include_usage?: boolean | undefined;
};

/** @internal */
export const ChatCompletionRequestStreamStreamOptions$outboundSchema: z.ZodType<
  ChatCompletionRequestStreamStreamOptions$Outbound,
  z.ZodTypeDef,
  ChatCompletionRequestStreamStreamOptions
> = z.object({
  includeUsage: z.boolean().optional(),
}).transform((v) => {
  return remap$(v, {
    includeUsage: "include_usage",
  });
});

export function chatCompletionRequestStreamStreamOptionsToJSON(
  chatCompletionRequestStreamStreamOptions:
    ChatCompletionRequestStreamStreamOptions,
): string {
  return JSON.stringify(
    ChatCompletionRequestStreamStreamOptions$outboundSchema.parse(
      chatCompletionRequestStreamStreamOptions,
    ),
  );
}

/** @internal */
export const ChatCompletionRequestStreamToolChoiceType$outboundSchema:
  z.ZodNativeEnum<typeof ChatCompletionRequestStreamToolChoiceType> = z
    .nativeEnum(ChatCompletionRequestStreamToolChoiceType);

/** @internal */
export type ChatCompletionRequestStreamFunction$Outbound = {
  name: string;
};

/** @internal */
export const ChatCompletionRequestStreamFunction$outboundSchema: z.ZodType<
  ChatCompletionRequestStreamFunction$Outbound,
  z.ZodTypeDef,
  ChatCompletionRequestStreamFunction
> = z.object({
  name: z.string(),
});

export function chatCompletionRequestStreamFunctionToJSON(
  chatCompletionRequestStreamFunction: ChatCompletionRequestStreamFunction,
): string {
  return JSON.stringify(
    ChatCompletionRequestStreamFunction$outboundSchema.parse(
      chatCompletionRequestStreamFunction,
    ),
  );
}

/** @internal */
export type ChatCompletionRequestStreamToolChoiceFunction$Outbound = {
  type: string;
  function: ChatCompletionRequestStreamFunction$Outbound;
};

/** @internal */
export const ChatCompletionRequestStreamToolChoiceFunction$outboundSchema:
  z.ZodType<
    ChatCompletionRequestStreamToolChoiceFunction$Outbound,
    z.ZodTypeDef,
    ChatCompletionRequestStreamToolChoiceFunction
  > = z.object({
    type: ChatCompletionRequestStreamToolChoiceType$outboundSchema,
    function: z.lazy(() => ChatCompletionRequestStreamFunction$outboundSchema),
  });

export function chatCompletionRequestStreamToolChoiceFunctionToJSON(
  chatCompletionRequestStreamToolChoiceFunction:
    ChatCompletionRequestStreamToolChoiceFunction,
): string {
  return JSON.stringify(
    ChatCompletionRequestStreamToolChoiceFunction$outboundSchema.parse(
      chatCompletionRequestStreamToolChoiceFunction,
    ),
  );
}

/** @internal */
export const ChatCompletionRequestStreamToolChoiceEnum$outboundSchema:
  z.ZodNativeEnum<typeof ChatCompletionRequestStreamToolChoiceEnum> = z
    .nativeEnum(ChatCompletionRequestStreamToolChoiceEnum);

/** @internal */
export type ChatCompletionRequestStreamToolChoiceUnion$Outbound =
  | ChatCompletionRequestStreamToolChoiceFunction$Outbound
  | string;

/** @internal */
export const ChatCompletionRequestStreamToolChoiceUnion$outboundSchema:
  z.ZodType<
    ChatCompletionRequestStreamToolChoiceUnion$Outbound,
    z.ZodTypeDef,
    ChatCompletionRequestStreamToolChoiceUnion
  > = z.union([
    z.lazy(() => ChatCompletionRequestStreamToolChoiceFunction$outboundSchema),
    ChatCompletionRequestStreamToolChoiceEnum$outboundSchema,
  ]);

export function chatCompletionRequestStreamToolChoiceUnionToJSON(
  chatCompletionRequestStreamToolChoiceUnion:
    ChatCompletionRequestStreamToolChoiceUnion,
): string {
  return JSON.stringify(
    ChatCompletionRequestStreamToolChoiceUnion$outboundSchema.parse(
      chatCompletionRequestStreamToolChoiceUnion,
    ),
  );
}

/** @internal */
export type ChatCompletionRequestStream$Outbound = {
  audio?: ChatCompletionRequestStreamAudio$Outbound | null | undefined;
  frequency_penalty?: number | null | undefined;
  logit_bias?: { [k: string]: number } | null | undefined;
  logprobs?: boolean | null | undefined;
  max_completion_tokens?: number | null | undefined;
  messages: Array<ChatMessage$Outbound>;
  metadata?: { [k: string]: string } | null | undefined;
  modalities?: Array<string> | null | undefined;
  model: string;
  n?: number | null | undefined;
  parallel_tool_calls?: boolean | null | undefined;
  prediction?:
    | ChatCompletionRequestStreamPrediction$Outbound
    | null
    | undefined;
  presence_penalty?: number | null | undefined;
  prompt_cache_key?: string | null | undefined;
  reasoning_effort?: string | null | undefined;
  response_format?:
    | ChatCompletionRequestStreamResponseFormatJSONSchema$Outbound
    | ChatCompletionRequestStreamResponseFormatText$Outbound
    | ChatCompletionRequestStreamResponseFormatJSONObject$Outbound
    | null
    | undefined;
  seed?: number | null | undefined;
  service_tier?: string | null | undefined;
  stop?: Array<string> | null | undefined;
  store?: boolean | null | undefined;
  stream: boolean;
  stream_options?:
    | ChatCompletionRequestStreamStreamOptions$Outbound
    | null
    | undefined;
  temperature?: number | null | undefined;
  tool_choice?:
    | ChatCompletionRequestStreamToolChoiceFunction$Outbound
    | string
    | null
    | undefined;
  tools?: Array<Tool$Outbound> | null | undefined;
  top_logprobs?: number | null | undefined;
  top_p?: number | null | undefined;
  user?: string | null | undefined;
};

/** @internal */
export const ChatCompletionRequestStream$outboundSchema: z.ZodType<
  ChatCompletionRequestStream$Outbound,
  z.ZodTypeDef,
  ChatCompletionRequestStream
> = z.object({
  audio: z.nullable(
    z.lazy(() => ChatCompletionRequestStreamAudio$outboundSchema),
  ).optional(),
  frequencyPenalty: z.nullable(z.number()).optional(),
  logitBias: z.nullable(z.record(z.number())).optional(),
  logprobs: z.nullable(z.boolean()).optional(),
  maxCompletionTokens: z.nullable(z.number().int()).optional(),
  messages: z.array(ChatMessage$outboundSchema),
  metadata: z.nullable(z.record(z.string())).optional(),
  modalities: z.nullable(
    z.array(ChatCompletionRequestStreamModality$outboundSchema),
  ).optional(),
  model: z.string(),
  n: z.nullable(z.number().int()).optional(),
  parallelToolCalls: z.nullable(z.boolean()).optional(),
  prediction: z.nullable(
    z.lazy(() => ChatCompletionRequestStreamPrediction$outboundSchema),
  ).optional(),
  presencePenalty: z.nullable(z.number()).optional(),
  promptCacheKey: z.nullable(z.string()).optional(),
  reasoningEffort: z.nullable(
    ChatCompletionRequestStreamReasoningEffort$outboundSchema,
  ).optional(),
  responseFormat: z.nullable(
    z.union([
      z.lazy(() =>
        ChatCompletionRequestStreamResponseFormatJSONSchema$outboundSchema
      ),
      z.lazy(() =>
        ChatCompletionRequestStreamResponseFormatText$outboundSchema
      ),
      z.lazy(() =>
        ChatCompletionRequestStreamResponseFormatJSONObject$outboundSchema
      ),
    ]),
  ).optional(),
  seed: z.nullable(z.number().int()).optional(),
  serviceTier: z.nullable(ChatCompletionRequestStreamServiceTier$outboundSchema)
    .optional(),
  stop: z.nullable(z.array(z.string())).optional(),
  store: z.nullable(z.boolean()).optional(),
  stream: z.boolean().default(true),
  streamOptions: z.nullable(
    z.lazy(() => ChatCompletionRequestStreamStreamOptions$outboundSchema),
  ).optional(),
  temperature: z.nullable(z.number()).optional(),
  toolChoice: z.nullable(
    z.union([
      z.lazy(() =>
        ChatCompletionRequestStreamToolChoiceFunction$outboundSchema
      ),
      ChatCompletionRequestStreamToolChoiceEnum$outboundSchema,
    ]),
  ).optional(),
  tools: z.nullable(z.array(Tool$outboundSchema)).optional(),
  topLogprobs: z.nullable(z.number().int()).optional(),
  topP: z.nullable(z.number()).optional(),
  user: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    frequencyPenalty: "frequency_penalty",
    logitBias: "logit_bias",
    maxCompletionTokens: "max_completion_tokens",
    parallelToolCalls: "parallel_tool_calls",
    presencePenalty: "presence_penalty",
    promptCacheKey: "prompt_cache_key",
    reasoningEffort: "reasoning_effort",
    responseFormat: "response_format",
    serviceTier: "service_tier",
    streamOptions: "stream_options",
    toolChoice: "tool_choice",
    topLogprobs: "top_logprobs",
    topP: "top_p",
  });
});

export function chatCompletionRequestStreamToJSON(
  chatCompletionRequestStream: ChatCompletionRequestStream,
): string {
  return JSON.stringify(
    ChatCompletionRequestStream$outboundSchema.parse(
      chatCompletionRequestStream,
    ),
  );
}
