/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type ChatDeletionConfirmation = {
  deleted: boolean;
  id: string;
  object: string;
};

/** @internal */
export const ChatDeletionConfirmation$inboundSchema: z.ZodType<
  ChatDeletionConfirmation,
  z.ZodTypeDef,
  unknown
> = z.object({
  deleted: z.boolean(),
  id: z.string(),
  object: z.string(),
});

export function chatDeletionConfirmationFromJSON(
  jsonString: string,
): SafeParseResult<ChatDeletionConfirmation, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChatDeletionConfirmation$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChatDeletionConfirmation' from JSON`,
  );
}
