/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  MessageContent,
  MessageContent$inboundSchema,
  MessageContent$Outbound,
  MessageContent$outboundSchema,
} from "./messagecontent.js";
import {
  ToolCall,
  ToolCall$inboundSchema,
  ToolCall$Outbound,
  ToolCall$outboundSchema,
} from "./toolcall.js";

export type ChatMessage = {
  content: MessageContent;
  name?: string | null | undefined;
  role: string;
  toolCallId?: string | null | undefined;
  toolCalls?: Array<ToolCall> | null | undefined;
};

/** @internal */
export const ChatMessage$inboundSchema: z.ZodType<
  ChatMessage,
  z.ZodTypeDef,
  unknown
> = z.object({
  content: MessageContent$inboundSchema,
  name: z.nullable(z.string()).optional(),
  role: z.string(),
  tool_call_id: z.nullable(z.string()).optional(),
  tool_calls: z.nullable(z.array(ToolCall$inboundSchema)).optional(),
}).transform((v) => {
  return remap$(v, {
    "tool_call_id": "toolCallId",
    "tool_calls": "toolCalls",
  });
});

/** @internal */
export type ChatMessage$Outbound = {
  content: MessageContent$Outbound;
  name?: string | null | undefined;
  role: string;
  tool_call_id?: string | null | undefined;
  tool_calls?: Array<ToolCall$Outbound> | null | undefined;
};

/** @internal */
export const ChatMessage$outboundSchema: z.ZodType<
  ChatMessage$Outbound,
  z.ZodTypeDef,
  ChatMessage
> = z.object({
  content: MessageContent$outboundSchema,
  name: z.nullable(z.string()).optional(),
  role: z.string(),
  toolCallId: z.nullable(z.string()).optional(),
  toolCalls: z.nullable(z.array(ToolCall$outboundSchema)).optional(),
}).transform((v) => {
  return remap$(v, {
    toolCallId: "tool_call_id",
    toolCalls: "tool_calls",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ChatMessage$ {
  /** @deprecated use `ChatMessage$inboundSchema` instead. */
  export const inboundSchema = ChatMessage$inboundSchema;
  /** @deprecated use `ChatMessage$outboundSchema` instead. */
  export const outboundSchema = ChatMessage$outboundSchema;
  /** @deprecated use `ChatMessage$Outbound` instead. */
  export type Outbound = ChatMessage$Outbound;
}

export function chatMessageToJSON(chatMessage: ChatMessage): string {
  return JSON.stringify(ChatMessage$outboundSchema.parse(chatMessage));
}

export function chatMessageFromJSON(
  jsonString: string,
): SafeParseResult<ChatMessage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChatMessage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChatMessage' from JSON`,
  );
}
