/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { ClosedEnum } from "../types/enums.js";
import {
  ChatMessage,
  ChatMessage$Outbound,
  ChatMessage$outboundSchema,
} from "./chatmessage.js";
import { Tool, Tool$Outbound, Tool$outboundSchema } from "./tool.js";

/**
 * Specifies the output audio format. Must be one of wav, mp3, flac, opus, or pcm16.
 */
export const ChatCompletionRequestJsonFormat = {
  Wav: "wav",
  Mp3: "mp3",
  Flac: "flac",
  Opus: "opus",
  Pcm16: "pcm16",
} as const;
/**
 * Specifies the output audio format. Must be one of wav, mp3, flac, opus, or pcm16.
 */
export type ChatCompletionRequestJsonFormat = ClosedEnum<
  typeof ChatCompletionRequestJsonFormat
>;

/**
 * Specifies the voice type. Supported voices are alloy, echo, fable, onyx, nova, and shimmer.
 */
export const ChatCompletionRequestJsonVoice = {
  Alloy: "alloy",
  Echo: "echo",
  Fable: "fable",
  Onyx: "onyx",
  Nova: "nova",
  Shimmer: "shimmer",
} as const;
/**
 * Specifies the voice type. Supported voices are alloy, echo, fable, onyx, nova, and shimmer.
 */
export type ChatCompletionRequestJsonVoice = ClosedEnum<
  typeof ChatCompletionRequestJsonVoice
>;

/**
 * Parameters for audio output. Required when audio output is requested with modalities: ["audio"].
 */
export type ChatCompletionRequestJsonAudio = {
  /**
   * Specifies the output audio format. Must be one of wav, mp3, flac, opus, or pcm16.
   */
  format?: ChatCompletionRequestJsonFormat | undefined;
  /**
   * Specifies the voice type. Supported voices are alloy, echo, fable, onyx, nova, and shimmer.
   */
  voice?: ChatCompletionRequestJsonVoice | undefined;
};

export const ChatCompletionRequestJsonModality = {
  Text: "text",
  Audio: "audio",
} as const;
export type ChatCompletionRequestJsonModality = ClosedEnum<
  typeof ChatCompletionRequestJsonModality
>;

export const ChatCompletionRequestJsonTypeContent = {
  Content: "content",
} as const;
export type ChatCompletionRequestJsonTypeContent = ClosedEnum<
  typeof ChatCompletionRequestJsonTypeContent
>;

/**
 * Configuration for a Predicted Output, which can greatly improve response times when large parts of the model response are known ahead of time. This is most common when you are regenerating a file with only minor changes to most of the content.
 */
export type ChatCompletionRequestJsonPrediction = {
  type?: ChatCompletionRequestJsonTypeContent | undefined;
  /**
   * The predicted content for the completion.
   */
  content?: string | undefined;
};

/**
 * o1 models only. Constrains effort on reasoning for reasoning models. Currently supported values are low, medium, and high. Reducing reasoning effort can result in faster responses and fewer tokens used on reasoning in a response.
 */
export const ChatCompletionRequestJsonReasoningEffort = {
  Low: "low",
  Medium: "medium",
  High: "high",
} as const;
/**
 * o1 models only. Constrains effort on reasoning for reasoning models. Currently supported values are low, medium, and high. Reducing reasoning effort can result in faster responses and fewer tokens used on reasoning in a response.
 */
export type ChatCompletionRequestJsonReasoningEffort = ClosedEnum<
  typeof ChatCompletionRequestJsonReasoningEffort
>;

export const ChatCompletionRequestJSONTypeJSONSchema = {
  JsonSchema: "json_schema",
} as const;
export type ChatCompletionRequestJSONTypeJSONSchema = ClosedEnum<
  typeof ChatCompletionRequestJSONTypeJSONSchema
>;

/**
 * The JSON schema definition for structured outputs.
 */
export type ChatCompletionRequestJsonJsonSchema = {
  /**
   * The name of the response format. Must be a-z, A-Z, 0-9, or contain underscores and dashes, with a maximum length of 64.
   */
  name: string;
  /**
   * A description of what the response format is for, used by the model to determine how to respond in the format.
   */
  description?: string | undefined;
  /**
   * The schema for the response format, described as a JSON Schema object.
   */
  schema: { [k: string]: any };
  /**
   * Whether to enable strict schema adherence when generating the output.
   */
  strict?: boolean | undefined;
};

export type ChatCompletionRequestJSONResponseFormatJSONSchema = {
  type: ChatCompletionRequestJSONTypeJSONSchema;
  /**
   * The JSON schema definition for structured outputs.
   */
  jsonSchema: ChatCompletionRequestJsonJsonSchema;
};

export const ChatCompletionRequestJSONTypeJSONObject = {
  JsonObject: "json_object",
} as const;
export type ChatCompletionRequestJSONTypeJSONObject = ClosedEnum<
  typeof ChatCompletionRequestJSONTypeJSONObject
>;

export type ChatCompletionRequestJSONResponseFormatJSONObject = {
  type: ChatCompletionRequestJSONTypeJSONObject;
};

export const ChatCompletionRequestJsonTypeText = {
  Text: "text",
} as const;
export type ChatCompletionRequestJsonTypeText = ClosedEnum<
  typeof ChatCompletionRequestJsonTypeText
>;

export type ChatCompletionRequestJsonResponseFormatText = {
  type: ChatCompletionRequestJsonTypeText;
};

/**
 * An object specifying the format that the model must output. Compatible with GPT-4o, GPT-4o mini, GPT-4 Turbo and all GPT-3.5 Turbo models newer than gpt-3.5-turbo-1106. Setting to { "type": "json_schema", "json_schema": {...} } enables Structured Outputs which guarantee the model will match your supplied JSON schema. Setting to { "type": "json_object" } enables JSON mode, which guarantees the message the model generates is valid JSON.
 */
export type ChatCompletionRequestJsonResponseFormatUnion =
  | ChatCompletionRequestJSONResponseFormatJSONSchema
  | ChatCompletionRequestJsonResponseFormatText
  | ChatCompletionRequestJSONResponseFormatJSONObject;

/**
 * Specifies the latency tier to use for processing the request. This parameter is relevant for customers subscribed to the scale tier service.
 */
export const ChatCompletionRequestJsonServiceTier = {
  Auto: "auto",
  Default: "default",
} as const;
/**
 * Specifies the latency tier to use for processing the request. This parameter is relevant for customers subscribed to the scale tier service.
 */
export type ChatCompletionRequestJsonServiceTier = ClosedEnum<
  typeof ChatCompletionRequestJsonServiceTier
>;

/**
 * Options for streaming response. Only set this when you set stream: true.
 */
export type ChatCompletionRequestJsonStreamOptions = {
  /**
   * If set, an additional chunk will be streamed before the data: [DONE] message. The usage field on this chunk shows the token usage statistics for the entire request, and the choices field will always be an empty array. All other chunks will also include a usage field, but with a null value.
   */
  includeUsage?: boolean | undefined;
};

export const ChatCompletionRequestJsonToolChoiceType = {
  Function: "function",
} as const;
export type ChatCompletionRequestJsonToolChoiceType = ClosedEnum<
  typeof ChatCompletionRequestJsonToolChoiceType
>;

export type ChatCompletionRequestJsonFunction = {
  name: string;
};

export type ChatCompletionRequestJsonToolChoiceFunction = {
  type: ChatCompletionRequestJsonToolChoiceType;
  function: ChatCompletionRequestJsonFunction;
};

export const ChatCompletionRequestJsonToolChoiceEnum = {
  None: "none",
  Auto: "auto",
  Required: "required",
} as const;
export type ChatCompletionRequestJsonToolChoiceEnum = ClosedEnum<
  typeof ChatCompletionRequestJsonToolChoiceEnum
>;

/**
 * Controls which (if any) tool is called by the model. none means the model won't call any tool and instead generates a message. auto means the model can pick between generating a message or calling one or more tools. required means the model must call one or more tools. Specifying a particular tool via {"type": "function", "function": {"name": "my_function"}} forces the model to call that tool. none is the default when no tools are present. auto is the default if tools are present.
 */
export type ChatCompletionRequestJsonToolChoiceUnion =
  | ChatCompletionRequestJsonToolChoiceFunction
  | ChatCompletionRequestJsonToolChoiceEnum;

export type ChatCompletionRequestJson = {
  /**
   * Parameters for audio output. Required when audio output is requested with modalities: ["audio"].
   */
  audio?: ChatCompletionRequestJsonAudio | null | undefined;
  /**
   * Number between -2.0 and 2.0. Positive values penalize new tokens based on their existing frequency in the text so far, decreasing the model's likelihood to repeat the same line verbatim.
   */
  frequencyPenalty?: number | null | undefined;
  /**
   * Modify the likelihood of specified tokens appearing in the completion. Accepts a JSON object that maps tokens (specified by their token ID in the tokenizer) to an associated bias value from -100 to 100. Mathematically, the bias is added to the logits generated by the model prior to sampling. The exact effect will vary per model, but values between -1 and 1 should decrease or increase likelihood of selection; values like -100 or 100 should result in a ban or exclusive selection of the relevant token.
   */
  logitBias?: { [k: string]: number } | null | undefined;
  /**
   * Whether to return log probabilities of the output tokens or not. If true, returns the log probabilities of each output token returned in the content of message.
   */
  logprobs?: boolean | null | undefined;
  /**
   * An upper bound for the number of tokens that can be generated for a completion, including visible output tokens and reasoning tokens.
   */
  maxCompletionTokens?: number | null | undefined;
  /**
   * A list of messages comprising the conversation so far. Depending on the model you use, different message types (modalities) are supported, like text, images, and audio.
   */
  messages: Array<ChatMessage>;
  /**
   * Developer-defined tags and values used for filtering completions in the stored completions dashboard.
   */
  metadata?: { [k: string]: string } | null | undefined;
  /**
   * Output types that you would like the model to generate for this request. Most models are capable of generating text, which is the default: ["text"]. The gpt-4o-audio-preview model can also be used to generate audio. To request that this model generate both text and audio responses, you can use: ["text", "audio"].
   */
  modalities?: Array<ChatCompletionRequestJsonModality> | null | undefined;
  /**
   * Model name used to generate the response, like gpt-4o or deepseek-reasoner. Sudo offers a wide range of models with different capabilities, performance characteristics, and price points. Refer to the [docs](https://docs.sudoapp.dev/overview/models) to browse and compare available models.
   */
  model: string;
  /**
   * How many chat completion choices to generate for each input message. Note that you will be charged based on the number of generated tokens across all of the choices. Keep n as 1 to minimize costs.
   */
  n?: number | null | undefined;
  /**
   * Whether to enable parallel function calling during tool use.
   */
  parallelToolCalls?: boolean | null | undefined;
  /**
   * Configuration for a Predicted Output, which can greatly improve response times when large parts of the model response are known ahead of time. This is most common when you are regenerating a file with only minor changes to most of the content.
   */
  prediction?: ChatCompletionRequestJsonPrediction | null | undefined;
  /**
   * Number between -2.0 and 2.0. Positive values penalize new tokens based on whether they appear in the text so far, increasing the model's likelihood to talk about new topics.
   */
  presencePenalty?: number | null | undefined;
  /**
   * A unique identifier for caching prompts to improve response times for repeated requests.
   */
  promptCacheKey?: string | null | undefined;
  /**
   * o1 models only. Constrains effort on reasoning for reasoning models. Currently supported values are low, medium, and high. Reducing reasoning effort can result in faster responses and fewer tokens used on reasoning in a response.
   */
  reasoningEffort?: ChatCompletionRequestJsonReasoningEffort | null | undefined;
  /**
   * An object specifying the format that the model must output. Compatible with GPT-4o, GPT-4o mini, GPT-4 Turbo and all GPT-3.5 Turbo models newer than gpt-3.5-turbo-1106. Setting to { "type": "json_schema", "json_schema": {...} } enables Structured Outputs which guarantee the model will match your supplied JSON schema. Setting to { "type": "json_object" } enables JSON mode, which guarantees the message the model generates is valid JSON.
   */
  responseFormat?:
    | ChatCompletionRequestJSONResponseFormatJSONSchema
    | ChatCompletionRequestJsonResponseFormatText
    | ChatCompletionRequestJSONResponseFormatJSONObject
    | null
    | undefined;
  /**
   * If specified, our system will make a best effort to sample deterministically, such that repeated requests with the same seed and parameters should return the same result. Determinism isn't guaranteed, and you should refer to the system_fingerprint response parameter to monitor changes in the backend.
   */
  seed?: number | null | undefined;
  /**
   * Specifies the latency tier to use for processing the request. This parameter is relevant for customers subscribed to the scale tier service.
   */
  serviceTier?: ChatCompletionRequestJsonServiceTier | null | undefined;
  /**
   * Not supported with latest reasoning models o3 and o4-mini. Up to 4 sequences where the API will stop generating further tokens. The returned text will not contain the stop sequence.
   */
  stop?: Array<string> | null | undefined;
  /**
   * Whether or not to store the output of this chat completion request for use in our model distillation or evaluation products.
   */
  store?: boolean | null | undefined;
  /**
   * If set, partial message deltas will be sent, like in ChatGPT. For JSON responses, this must be false.
   */
  stream?: boolean | undefined;
  /**
   * Options for streaming response. Only set this when you set stream: true.
   */
  streamOptions?: ChatCompletionRequestJsonStreamOptions | null | undefined;
  /**
   * What sampling temperature to use, between 0 and 2. Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic. We generally recommend altering this or top_p but not both.
   */
  temperature?: number | null | undefined;
  /**
   * Controls which (if any) tool is called by the model. none means the model won't call any tool and instead generates a message. auto means the model can pick between generating a message or calling one or more tools. required means the model must call one or more tools. Specifying a particular tool via {"type": "function", "function": {"name": "my_function"}} forces the model to call that tool. none is the default when no tools are present. auto is the default if tools are present.
   */
  toolChoice?:
    | ChatCompletionRequestJsonToolChoiceFunction
    | ChatCompletionRequestJsonToolChoiceEnum
    | null
    | undefined;
  /**
   * A list of tools the model may call. Currently, only functions are supported as a tool. Use this to provide a list of functions the model may generate JSON inputs for. A max of 128 functions are supported.
   */
  tools?: Array<Tool> | null | undefined;
  /**
   * An integer between 0 and 20 specifying the number of most likely tokens to return at each token position, each with an associated log probability. logprobs must be set to true if this parameter is used.
   */
  topLogprobs?: number | null | undefined;
  /**
   * An alternative to sampling with temperature, called nucleus sampling, where the model considers the results of the tokens with top_p probability mass. So 0.1 means only the tokens comprising the top 10% probability mass are considered. We generally recommend altering this or temperature but not both.
   */
  topP?: number | null | undefined;
};

/** @internal */
export const ChatCompletionRequestJsonFormat$outboundSchema: z.ZodNativeEnum<
  typeof ChatCompletionRequestJsonFormat
> = z.nativeEnum(ChatCompletionRequestJsonFormat);

/** @internal */
export const ChatCompletionRequestJsonVoice$outboundSchema: z.ZodNativeEnum<
  typeof ChatCompletionRequestJsonVoice
> = z.nativeEnum(ChatCompletionRequestJsonVoice);

/** @internal */
export type ChatCompletionRequestJsonAudio$Outbound = {
  format?: string | undefined;
  voice?: string | undefined;
};

/** @internal */
export const ChatCompletionRequestJsonAudio$outboundSchema: z.ZodType<
  ChatCompletionRequestJsonAudio$Outbound,
  z.ZodTypeDef,
  ChatCompletionRequestJsonAudio
> = z.object({
  format: ChatCompletionRequestJsonFormat$outboundSchema.optional(),
  voice: ChatCompletionRequestJsonVoice$outboundSchema.optional(),
});

export function chatCompletionRequestJsonAudioToJSON(
  chatCompletionRequestJsonAudio: ChatCompletionRequestJsonAudio,
): string {
  return JSON.stringify(
    ChatCompletionRequestJsonAudio$outboundSchema.parse(
      chatCompletionRequestJsonAudio,
    ),
  );
}

/** @internal */
export const ChatCompletionRequestJsonModality$outboundSchema: z.ZodNativeEnum<
  typeof ChatCompletionRequestJsonModality
> = z.nativeEnum(ChatCompletionRequestJsonModality);

/** @internal */
export const ChatCompletionRequestJsonTypeContent$outboundSchema:
  z.ZodNativeEnum<typeof ChatCompletionRequestJsonTypeContent> = z.nativeEnum(
    ChatCompletionRequestJsonTypeContent,
  );

/** @internal */
export type ChatCompletionRequestJsonPrediction$Outbound = {
  type?: string | undefined;
  content?: string | undefined;
};

/** @internal */
export const ChatCompletionRequestJsonPrediction$outboundSchema: z.ZodType<
  ChatCompletionRequestJsonPrediction$Outbound,
  z.ZodTypeDef,
  ChatCompletionRequestJsonPrediction
> = z.object({
  type: ChatCompletionRequestJsonTypeContent$outboundSchema.optional(),
  content: z.string().optional(),
});

export function chatCompletionRequestJsonPredictionToJSON(
  chatCompletionRequestJsonPrediction: ChatCompletionRequestJsonPrediction,
): string {
  return JSON.stringify(
    ChatCompletionRequestJsonPrediction$outboundSchema.parse(
      chatCompletionRequestJsonPrediction,
    ),
  );
}

/** @internal */
export const ChatCompletionRequestJsonReasoningEffort$outboundSchema:
  z.ZodNativeEnum<typeof ChatCompletionRequestJsonReasoningEffort> = z
    .nativeEnum(ChatCompletionRequestJsonReasoningEffort);

/** @internal */
export const ChatCompletionRequestJSONTypeJSONSchema$outboundSchema:
  z.ZodNativeEnum<typeof ChatCompletionRequestJSONTypeJSONSchema> = z
    .nativeEnum(ChatCompletionRequestJSONTypeJSONSchema);

/** @internal */
export type ChatCompletionRequestJsonJsonSchema$Outbound = {
  name: string;
  description?: string | undefined;
  schema: { [k: string]: any };
  strict?: boolean | undefined;
};

/** @internal */
export const ChatCompletionRequestJsonJsonSchema$outboundSchema: z.ZodType<
  ChatCompletionRequestJsonJsonSchema$Outbound,
  z.ZodTypeDef,
  ChatCompletionRequestJsonJsonSchema
> = z.object({
  name: z.string(),
  description: z.string().optional(),
  schema: z.record(z.any()),
  strict: z.boolean().optional(),
});

export function chatCompletionRequestJsonJsonSchemaToJSON(
  chatCompletionRequestJsonJsonSchema: ChatCompletionRequestJsonJsonSchema,
): string {
  return JSON.stringify(
    ChatCompletionRequestJsonJsonSchema$outboundSchema.parse(
      chatCompletionRequestJsonJsonSchema,
    ),
  );
}

/** @internal */
export type ChatCompletionRequestJSONResponseFormatJSONSchema$Outbound = {
  type: string;
  json_schema: ChatCompletionRequestJsonJsonSchema$Outbound;
};

/** @internal */
export const ChatCompletionRequestJSONResponseFormatJSONSchema$outboundSchema:
  z.ZodType<
    ChatCompletionRequestJSONResponseFormatJSONSchema$Outbound,
    z.ZodTypeDef,
    ChatCompletionRequestJSONResponseFormatJSONSchema
  > = z.object({
    type: ChatCompletionRequestJSONTypeJSONSchema$outboundSchema,
    jsonSchema: z.lazy(() =>
      ChatCompletionRequestJsonJsonSchema$outboundSchema
    ),
  }).transform((v) => {
    return remap$(v, {
      jsonSchema: "json_schema",
    });
  });

export function chatCompletionRequestJSONResponseFormatJSONSchemaToJSON(
  chatCompletionRequestJSONResponseFormatJSONSchema:
    ChatCompletionRequestJSONResponseFormatJSONSchema,
): string {
  return JSON.stringify(
    ChatCompletionRequestJSONResponseFormatJSONSchema$outboundSchema.parse(
      chatCompletionRequestJSONResponseFormatJSONSchema,
    ),
  );
}

/** @internal */
export const ChatCompletionRequestJSONTypeJSONObject$outboundSchema:
  z.ZodNativeEnum<typeof ChatCompletionRequestJSONTypeJSONObject> = z
    .nativeEnum(ChatCompletionRequestJSONTypeJSONObject);

/** @internal */
export type ChatCompletionRequestJSONResponseFormatJSONObject$Outbound = {
  type: string;
};

/** @internal */
export const ChatCompletionRequestJSONResponseFormatJSONObject$outboundSchema:
  z.ZodType<
    ChatCompletionRequestJSONResponseFormatJSONObject$Outbound,
    z.ZodTypeDef,
    ChatCompletionRequestJSONResponseFormatJSONObject
  > = z.object({
    type: ChatCompletionRequestJSONTypeJSONObject$outboundSchema,
  });

export function chatCompletionRequestJSONResponseFormatJSONObjectToJSON(
  chatCompletionRequestJSONResponseFormatJSONObject:
    ChatCompletionRequestJSONResponseFormatJSONObject,
): string {
  return JSON.stringify(
    ChatCompletionRequestJSONResponseFormatJSONObject$outboundSchema.parse(
      chatCompletionRequestJSONResponseFormatJSONObject,
    ),
  );
}

/** @internal */
export const ChatCompletionRequestJsonTypeText$outboundSchema: z.ZodNativeEnum<
  typeof ChatCompletionRequestJsonTypeText
> = z.nativeEnum(ChatCompletionRequestJsonTypeText);

/** @internal */
export type ChatCompletionRequestJsonResponseFormatText$Outbound = {
  type: string;
};

/** @internal */
export const ChatCompletionRequestJsonResponseFormatText$outboundSchema:
  z.ZodType<
    ChatCompletionRequestJsonResponseFormatText$Outbound,
    z.ZodTypeDef,
    ChatCompletionRequestJsonResponseFormatText
  > = z.object({
    type: ChatCompletionRequestJsonTypeText$outboundSchema,
  });

export function chatCompletionRequestJsonResponseFormatTextToJSON(
  chatCompletionRequestJsonResponseFormatText:
    ChatCompletionRequestJsonResponseFormatText,
): string {
  return JSON.stringify(
    ChatCompletionRequestJsonResponseFormatText$outboundSchema.parse(
      chatCompletionRequestJsonResponseFormatText,
    ),
  );
}

/** @internal */
export type ChatCompletionRequestJsonResponseFormatUnion$Outbound =
  | ChatCompletionRequestJSONResponseFormatJSONSchema$Outbound
  | ChatCompletionRequestJsonResponseFormatText$Outbound
  | ChatCompletionRequestJSONResponseFormatJSONObject$Outbound;

/** @internal */
export const ChatCompletionRequestJsonResponseFormatUnion$outboundSchema:
  z.ZodType<
    ChatCompletionRequestJsonResponseFormatUnion$Outbound,
    z.ZodTypeDef,
    ChatCompletionRequestJsonResponseFormatUnion
  > = z.union([
    z.lazy(() =>
      ChatCompletionRequestJSONResponseFormatJSONSchema$outboundSchema
    ),
    z.lazy(() => ChatCompletionRequestJsonResponseFormatText$outboundSchema),
    z.lazy(() =>
      ChatCompletionRequestJSONResponseFormatJSONObject$outboundSchema
    ),
  ]);

export function chatCompletionRequestJsonResponseFormatUnionToJSON(
  chatCompletionRequestJsonResponseFormatUnion:
    ChatCompletionRequestJsonResponseFormatUnion,
): string {
  return JSON.stringify(
    ChatCompletionRequestJsonResponseFormatUnion$outboundSchema.parse(
      chatCompletionRequestJsonResponseFormatUnion,
    ),
  );
}

/** @internal */
export const ChatCompletionRequestJsonServiceTier$outboundSchema:
  z.ZodNativeEnum<typeof ChatCompletionRequestJsonServiceTier> = z.nativeEnum(
    ChatCompletionRequestJsonServiceTier,
  );

/** @internal */
export type ChatCompletionRequestJsonStreamOptions$Outbound = {
  include_usage?: boolean | undefined;
};

/** @internal */
export const ChatCompletionRequestJsonStreamOptions$outboundSchema: z.ZodType<
  ChatCompletionRequestJsonStreamOptions$Outbound,
  z.ZodTypeDef,
  ChatCompletionRequestJsonStreamOptions
> = z.object({
  includeUsage: z.boolean().optional(),
}).transform((v) => {
  return remap$(v, {
    includeUsage: "include_usage",
  });
});

export function chatCompletionRequestJsonStreamOptionsToJSON(
  chatCompletionRequestJsonStreamOptions:
    ChatCompletionRequestJsonStreamOptions,
): string {
  return JSON.stringify(
    ChatCompletionRequestJsonStreamOptions$outboundSchema.parse(
      chatCompletionRequestJsonStreamOptions,
    ),
  );
}

/** @internal */
export const ChatCompletionRequestJsonToolChoiceType$outboundSchema:
  z.ZodNativeEnum<typeof ChatCompletionRequestJsonToolChoiceType> = z
    .nativeEnum(ChatCompletionRequestJsonToolChoiceType);

/** @internal */
export type ChatCompletionRequestJsonFunction$Outbound = {
  name: string;
};

/** @internal */
export const ChatCompletionRequestJsonFunction$outboundSchema: z.ZodType<
  ChatCompletionRequestJsonFunction$Outbound,
  z.ZodTypeDef,
  ChatCompletionRequestJsonFunction
> = z.object({
  name: z.string(),
});

export function chatCompletionRequestJsonFunctionToJSON(
  chatCompletionRequestJsonFunction: ChatCompletionRequestJsonFunction,
): string {
  return JSON.stringify(
    ChatCompletionRequestJsonFunction$outboundSchema.parse(
      chatCompletionRequestJsonFunction,
    ),
  );
}

/** @internal */
export type ChatCompletionRequestJsonToolChoiceFunction$Outbound = {
  type: string;
  function: ChatCompletionRequestJsonFunction$Outbound;
};

/** @internal */
export const ChatCompletionRequestJsonToolChoiceFunction$outboundSchema:
  z.ZodType<
    ChatCompletionRequestJsonToolChoiceFunction$Outbound,
    z.ZodTypeDef,
    ChatCompletionRequestJsonToolChoiceFunction
  > = z.object({
    type: ChatCompletionRequestJsonToolChoiceType$outboundSchema,
    function: z.lazy(() => ChatCompletionRequestJsonFunction$outboundSchema),
  });

export function chatCompletionRequestJsonToolChoiceFunctionToJSON(
  chatCompletionRequestJsonToolChoiceFunction:
    ChatCompletionRequestJsonToolChoiceFunction,
): string {
  return JSON.stringify(
    ChatCompletionRequestJsonToolChoiceFunction$outboundSchema.parse(
      chatCompletionRequestJsonToolChoiceFunction,
    ),
  );
}

/** @internal */
export const ChatCompletionRequestJsonToolChoiceEnum$outboundSchema:
  z.ZodNativeEnum<typeof ChatCompletionRequestJsonToolChoiceEnum> = z
    .nativeEnum(ChatCompletionRequestJsonToolChoiceEnum);

/** @internal */
export type ChatCompletionRequestJsonToolChoiceUnion$Outbound =
  | ChatCompletionRequestJsonToolChoiceFunction$Outbound
  | string;

/** @internal */
export const ChatCompletionRequestJsonToolChoiceUnion$outboundSchema: z.ZodType<
  ChatCompletionRequestJsonToolChoiceUnion$Outbound,
  z.ZodTypeDef,
  ChatCompletionRequestJsonToolChoiceUnion
> = z.union([
  z.lazy(() => ChatCompletionRequestJsonToolChoiceFunction$outboundSchema),
  ChatCompletionRequestJsonToolChoiceEnum$outboundSchema,
]);

export function chatCompletionRequestJsonToolChoiceUnionToJSON(
  chatCompletionRequestJsonToolChoiceUnion:
    ChatCompletionRequestJsonToolChoiceUnion,
): string {
  return JSON.stringify(
    ChatCompletionRequestJsonToolChoiceUnion$outboundSchema.parse(
      chatCompletionRequestJsonToolChoiceUnion,
    ),
  );
}

/** @internal */
export type ChatCompletionRequestJson$Outbound = {
  audio?: ChatCompletionRequestJsonAudio$Outbound | null | undefined;
  frequency_penalty?: number | null | undefined;
  logit_bias?: { [k: string]: number } | null | undefined;
  logprobs?: boolean | null | undefined;
  max_completion_tokens?: number | null | undefined;
  messages: Array<ChatMessage$Outbound>;
  metadata?: { [k: string]: string } | null | undefined;
  modalities?: Array<string> | null | undefined;
  model: string;
  n?: number | null | undefined;
  parallel_tool_calls?: boolean | null | undefined;
  prediction?: ChatCompletionRequestJsonPrediction$Outbound | null | undefined;
  presence_penalty?: number | null | undefined;
  prompt_cache_key?: string | null | undefined;
  reasoning_effort?: string | null | undefined;
  response_format?:
    | ChatCompletionRequestJSONResponseFormatJSONSchema$Outbound
    | ChatCompletionRequestJsonResponseFormatText$Outbound
    | ChatCompletionRequestJSONResponseFormatJSONObject$Outbound
    | null
    | undefined;
  seed?: number | null | undefined;
  service_tier?: string | null | undefined;
  stop?: Array<string> | null | undefined;
  store?: boolean | null | undefined;
  stream: boolean;
  stream_options?:
    | ChatCompletionRequestJsonStreamOptions$Outbound
    | null
    | undefined;
  temperature?: number | null | undefined;
  tool_choice?:
    | ChatCompletionRequestJsonToolChoiceFunction$Outbound
    | string
    | null
    | undefined;
  tools?: Array<Tool$Outbound> | null | undefined;
  top_logprobs?: number | null | undefined;
  top_p?: number | null | undefined;
};

/** @internal */
export const ChatCompletionRequestJson$outboundSchema: z.ZodType<
  ChatCompletionRequestJson$Outbound,
  z.ZodTypeDef,
  ChatCompletionRequestJson
> = z.object({
  audio: z.nullable(z.lazy(() => ChatCompletionRequestJsonAudio$outboundSchema))
    .optional(),
  frequencyPenalty: z.nullable(z.number()).optional(),
  logitBias: z.nullable(z.record(z.number())).optional(),
  logprobs: z.nullable(z.boolean()).optional(),
  maxCompletionTokens: z.nullable(z.number().int()).optional(),
  messages: z.array(ChatMessage$outboundSchema),
  metadata: z.nullable(z.record(z.string())).optional(),
  modalities: z.nullable(
    z.array(ChatCompletionRequestJsonModality$outboundSchema),
  ).optional(),
  model: z.string(),
  n: z.nullable(z.number().int()).optional(),
  parallelToolCalls: z.nullable(z.boolean()).optional(),
  prediction: z.nullable(
    z.lazy(() => ChatCompletionRequestJsonPrediction$outboundSchema),
  ).optional(),
  presencePenalty: z.nullable(z.number()).optional(),
  promptCacheKey: z.nullable(z.string()).optional(),
  reasoningEffort: z.nullable(
    ChatCompletionRequestJsonReasoningEffort$outboundSchema,
  ).optional(),
  responseFormat: z.nullable(
    z.union([
      z.lazy(() =>
        ChatCompletionRequestJSONResponseFormatJSONSchema$outboundSchema
      ),
      z.lazy(() => ChatCompletionRequestJsonResponseFormatText$outboundSchema),
      z.lazy(() =>
        ChatCompletionRequestJSONResponseFormatJSONObject$outboundSchema
      ),
    ]),
  ).optional(),
  seed: z.nullable(z.number().int()).optional(),
  serviceTier: z.nullable(ChatCompletionRequestJsonServiceTier$outboundSchema)
    .optional(),
  stop: z.nullable(z.array(z.string())).optional(),
  store: z.nullable(z.boolean()).optional(),
  stream: z.boolean().default(false),
  streamOptions: z.nullable(
    z.lazy(() => ChatCompletionRequestJsonStreamOptions$outboundSchema),
  ).optional(),
  temperature: z.nullable(z.number()).optional(),
  toolChoice: z.nullable(
    z.union([
      z.lazy(() => ChatCompletionRequestJsonToolChoiceFunction$outboundSchema),
      ChatCompletionRequestJsonToolChoiceEnum$outboundSchema,
    ]),
  ).optional(),
  tools: z.nullable(z.array(Tool$outboundSchema)).optional(),
  topLogprobs: z.nullable(z.number().int()).optional(),
  topP: z.nullable(z.number()).optional(),
}).transform((v) => {
  return remap$(v, {
    frequencyPenalty: "frequency_penalty",
    logitBias: "logit_bias",
    maxCompletionTokens: "max_completion_tokens",
    parallelToolCalls: "parallel_tool_calls",
    presencePenalty: "presence_penalty",
    promptCacheKey: "prompt_cache_key",
    reasoningEffort: "reasoning_effort",
    responseFormat: "response_format",
    serviceTier: "service_tier",
    streamOptions: "stream_options",
    toolChoice: "tool_choice",
    topLogprobs: "top_logprobs",
    topP: "top_p",
  });
});

export function chatCompletionRequestJsonToJSON(
  chatCompletionRequestJson: ChatCompletionRequestJson,
): string {
  return JSON.stringify(
    ChatCompletionRequestJson$outboundSchema.parse(chatCompletionRequestJson),
  );
}
