/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import {
  MessageContent,
  MessageContent$Outbound,
  MessageContent$outboundSchema,
} from "./messagecontent.js";
import {
  ToolCall,
  ToolCall$Outbound,
  ToolCall$outboundSchema,
} from "./toolcall.js";

export type ChatMessage = {
  content: MessageContent;
  name?: string | null | undefined;
  role: string;
  toolCallId?: string | null | undefined;
  toolCalls?: Array<ToolCall> | null | undefined;
};

/** @internal */
export type ChatMessage$Outbound = {
  content: MessageContent$Outbound;
  name?: string | null | undefined;
  role: string;
  tool_call_id?: string | null | undefined;
  tool_calls?: Array<ToolCall$Outbound> | null | undefined;
};

/** @internal */
export const ChatMessage$outboundSchema: z.ZodType<
  ChatMessage$Outbound,
  z.ZodTypeDef,
  ChatMessage
> = z.object({
  content: MessageContent$outboundSchema,
  name: z.nullable(z.string()).optional(),
  role: z.string(),
  toolCallId: z.nullable(z.string()).optional(),
  toolCalls: z.nullable(z.array(ToolCall$outboundSchema)).optional(),
}).transform((v) => {
  return remap$(v, {
    toolCallId: "tool_call_id",
    toolCalls: "tool_calls",
  });
});

export function chatMessageToJSON(chatMessage: ChatMessage): string {
  return JSON.stringify(ChatMessage$outboundSchema.parse(chatMessage));
}
