/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type ChatDeletionConfirmation = {
  deleted: boolean;
  id: string;
  object: string;
};

/** @internal */
export const ChatDeletionConfirmation$inboundSchema: z.ZodType<
  ChatDeletionConfirmation,
  z.ZodTypeDef,
  unknown
> = z.object({
  deleted: z.boolean(),
  id: z.string(),
  object: z.string(),
});

/** @internal */
export type ChatDeletionConfirmation$Outbound = {
  deleted: boolean;
  id: string;
  object: string;
};

/** @internal */
export const ChatDeletionConfirmation$outboundSchema: z.ZodType<
  ChatDeletionConfirmation$Outbound,
  z.ZodTypeDef,
  ChatDeletionConfirmation
> = z.object({
  deleted: z.boolean(),
  id: z.string(),
  object: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ChatDeletionConfirmation$ {
  /** @deprecated use `ChatDeletionConfirmation$inboundSchema` instead. */
  export const inboundSchema = ChatDeletionConfirmation$inboundSchema;
  /** @deprecated use `ChatDeletionConfirmation$outboundSchema` instead. */
  export const outboundSchema = ChatDeletionConfirmation$outboundSchema;
  /** @deprecated use `ChatDeletionConfirmation$Outbound` instead. */
  export type Outbound = ChatDeletionConfirmation$Outbound;
}

export function chatDeletionConfirmationToJSON(
  chatDeletionConfirmation: ChatDeletionConfirmation,
): string {
  return JSON.stringify(
    ChatDeletionConfirmation$outboundSchema.parse(chatDeletionConfirmation),
  );
}

export function chatDeletionConfirmationFromJSON(
  jsonString: string,
): SafeParseResult<ChatDeletionConfirmation, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChatDeletionConfirmation$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChatDeletionConfirmation' from JSON`,
  );
}
