/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { ToolCall, ToolCall$inboundSchema } from "./toolcall.js";

/**
 * The role of the author of this message.
 */
export const Role = {
  Assistant: "assistant",
  User: "user",
  System: "system",
  Tool: "tool",
} as const;
/**
 * The role of the author of this message.
 */
export type Role = ClosedEnum<typeof Role>;

export type ChatCompletionDelta = {
  /**
   * The contents of the chunk message.
   */
  content?: string | null | undefined;
  /**
   * The role of the author of this message.
   */
  role?: Role | null | undefined;
  /**
   * The tool calls generated by the model, such as function calls.
   */
  toolCalls?: Array<ToolCall> | null | undefined;
  /**
   * The refusal message generated by the model.
   */
  refusal?: string | null | undefined;
};

/** @internal */
export const Role$inboundSchema: z.ZodNativeEnum<typeof Role> = z.nativeEnum(
  Role,
);

/** @internal */
export const ChatCompletionDelta$inboundSchema: z.ZodType<
  ChatCompletionDelta,
  z.ZodTypeDef,
  unknown
> = z.object({
  content: z.nullable(z.string()).optional(),
  role: z.nullable(Role$inboundSchema).optional(),
  tool_calls: z.nullable(z.array(ToolCall$inboundSchema)).optional(),
  refusal: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "tool_calls": "toolCalls",
  });
});

export function chatCompletionDeltaFromJSON(
  jsonString: string,
): SafeParseResult<ChatCompletionDelta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChatCompletionDelta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChatCompletionDelta' from JSON`,
  );
}
