/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  ReturnedChatMessages,
  ReturnedChatMessages$inboundSchema,
} from "./returnedchatmessages.js";

export type ChatMessageList = {
  data: Array<ReturnedChatMessages>;
  firstId: string;
  hasMore: boolean;
  lastId: string;
  object: string;
};

/** @internal */
export const ChatMessageList$inboundSchema: z.ZodType<
  ChatMessageList,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(ReturnedChatMessages$inboundSchema),
  first_id: z.string(),
  has_more: z.boolean(),
  last_id: z.string(),
  object: z.string(),
}).transform((v) => {
  return remap$(v, {
    "first_id": "firstId",
    "has_more": "hasMore",
    "last_id": "lastId",
  });
});

export function chatMessageListFromJSON(
  jsonString: string,
): SafeParseResult<ChatMessageList, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChatMessageList$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChatMessageList' from JSON`,
  );
}
