/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  ChatCompletionChunkChoice,
  ChatCompletionChunkChoice$inboundSchema,
  ChatCompletionChunkChoice$Outbound,
  ChatCompletionChunkChoice$outboundSchema,
} from "./chatcompletionchunkchoice.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * The object type, which is always 'chat.completion.chunk'.
 */
export const ObjectT = {
  ChatCompletionChunk: "chat.completion.chunk",
} as const;
/**
 * The object type, which is always 'chat.completion.chunk'.
 */
export type ObjectT = ClosedEnum<typeof ObjectT>;

export type ChatCompletionChunkUsage = {
  completionTokens: number;
  completionTokensDetails?: any | undefined;
  promptTokens: number;
  promptTokensDetails?: any | undefined;
  totalTokens: number;
};

/**
 * Usage statistics for the completion request. Only present in the final chunk when stream_options.include_usage is set.
 */
export type UsageUnion = ChatCompletionChunkUsage;

export type Data = {
  /**
   * A unique identifier for the chat completion.
   */
  id: string;
  /**
   * The object type, which is always 'chat.completion.chunk'.
   */
  object: ObjectT;
  /**
   * The Unix timestamp (in seconds) of when the chat completion was created.
   */
  created: number;
  /**
   * The model used for the chat completion.
   */
  model: string;
  /**
   * This fingerprint represents the backend configuration that the model runs with.
   */
  systemFingerprint?: string | null | undefined;
  /**
   * A list of chat completion choices.
   */
  choices: Array<ChatCompletionChunkChoice>;
  /**
   * Usage statistics for the completion request. Only present in the final chunk when stream_options.include_usage is set.
   */
  usage?: ChatCompletionChunkUsage | null | undefined;
};

export type ChatCompletionChunk = {
  data?: Data | undefined;
};

/** @internal */
export const ObjectT$inboundSchema: z.ZodNativeEnum<typeof ObjectT> = z
  .nativeEnum(ObjectT);

/** @internal */
export const ObjectT$outboundSchema: z.ZodNativeEnum<typeof ObjectT> =
  ObjectT$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ObjectT$ {
  /** @deprecated use `ObjectT$inboundSchema` instead. */
  export const inboundSchema = ObjectT$inboundSchema;
  /** @deprecated use `ObjectT$outboundSchema` instead. */
  export const outboundSchema = ObjectT$outboundSchema;
}

/** @internal */
export const ChatCompletionChunkUsage$inboundSchema: z.ZodType<
  ChatCompletionChunkUsage,
  z.ZodTypeDef,
  unknown
> = z.object({
  completion_tokens: z.number().int(),
  completion_tokens_details: z.any().optional(),
  prompt_tokens: z.number().int(),
  prompt_tokens_details: z.any().optional(),
  total_tokens: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    "completion_tokens": "completionTokens",
    "completion_tokens_details": "completionTokensDetails",
    "prompt_tokens": "promptTokens",
    "prompt_tokens_details": "promptTokensDetails",
    "total_tokens": "totalTokens",
  });
});

/** @internal */
export type ChatCompletionChunkUsage$Outbound = {
  completion_tokens: number;
  completion_tokens_details?: any | undefined;
  prompt_tokens: number;
  prompt_tokens_details?: any | undefined;
  total_tokens: number;
};

/** @internal */
export const ChatCompletionChunkUsage$outboundSchema: z.ZodType<
  ChatCompletionChunkUsage$Outbound,
  z.ZodTypeDef,
  ChatCompletionChunkUsage
> = z.object({
  completionTokens: z.number().int(),
  completionTokensDetails: z.any().optional(),
  promptTokens: z.number().int(),
  promptTokensDetails: z.any().optional(),
  totalTokens: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    completionTokens: "completion_tokens",
    completionTokensDetails: "completion_tokens_details",
    promptTokens: "prompt_tokens",
    promptTokensDetails: "prompt_tokens_details",
    totalTokens: "total_tokens",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ChatCompletionChunkUsage$ {
  /** @deprecated use `ChatCompletionChunkUsage$inboundSchema` instead. */
  export const inboundSchema = ChatCompletionChunkUsage$inboundSchema;
  /** @deprecated use `ChatCompletionChunkUsage$outboundSchema` instead. */
  export const outboundSchema = ChatCompletionChunkUsage$outboundSchema;
  /** @deprecated use `ChatCompletionChunkUsage$Outbound` instead. */
  export type Outbound = ChatCompletionChunkUsage$Outbound;
}

export function chatCompletionChunkUsageToJSON(
  chatCompletionChunkUsage: ChatCompletionChunkUsage,
): string {
  return JSON.stringify(
    ChatCompletionChunkUsage$outboundSchema.parse(chatCompletionChunkUsage),
  );
}

export function chatCompletionChunkUsageFromJSON(
  jsonString: string,
): SafeParseResult<ChatCompletionChunkUsage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChatCompletionChunkUsage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChatCompletionChunkUsage' from JSON`,
  );
}

/** @internal */
export const UsageUnion$inboundSchema: z.ZodType<
  UsageUnion,
  z.ZodTypeDef,
  unknown
> = z.lazy(() => ChatCompletionChunkUsage$inboundSchema);

/** @internal */
export type UsageUnion$Outbound = ChatCompletionChunkUsage$Outbound;

/** @internal */
export const UsageUnion$outboundSchema: z.ZodType<
  UsageUnion$Outbound,
  z.ZodTypeDef,
  UsageUnion
> = z.lazy(() => ChatCompletionChunkUsage$outboundSchema);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UsageUnion$ {
  /** @deprecated use `UsageUnion$inboundSchema` instead. */
  export const inboundSchema = UsageUnion$inboundSchema;
  /** @deprecated use `UsageUnion$outboundSchema` instead. */
  export const outboundSchema = UsageUnion$outboundSchema;
  /** @deprecated use `UsageUnion$Outbound` instead. */
  export type Outbound = UsageUnion$Outbound;
}

export function usageUnionToJSON(usageUnion: UsageUnion): string {
  return JSON.stringify(UsageUnion$outboundSchema.parse(usageUnion));
}

export function usageUnionFromJSON(
  jsonString: string,
): SafeParseResult<UsageUnion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UsageUnion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UsageUnion' from JSON`,
  );
}

/** @internal */
export const Data$inboundSchema: z.ZodType<Data, z.ZodTypeDef, unknown> = z
  .object({
    id: z.string(),
    object: ObjectT$inboundSchema,
    created: z.number().int(),
    model: z.string(),
    system_fingerprint: z.nullable(z.string()).optional(),
    choices: z.array(ChatCompletionChunkChoice$inboundSchema),
    usage: z.nullable(z.lazy(() => ChatCompletionChunkUsage$inboundSchema))
      .optional(),
  }).transform((v) => {
    return remap$(v, {
      "system_fingerprint": "systemFingerprint",
    });
  });

/** @internal */
export type Data$Outbound = {
  id: string;
  object: string;
  created: number;
  model: string;
  system_fingerprint?: string | null | undefined;
  choices: Array<ChatCompletionChunkChoice$Outbound>;
  usage?: ChatCompletionChunkUsage$Outbound | null | undefined;
};

/** @internal */
export const Data$outboundSchema: z.ZodType<Data$Outbound, z.ZodTypeDef, Data> =
  z.object({
    id: z.string(),
    object: ObjectT$outboundSchema,
    created: z.number().int(),
    model: z.string(),
    systemFingerprint: z.nullable(z.string()).optional(),
    choices: z.array(ChatCompletionChunkChoice$outboundSchema),
    usage: z.nullable(z.lazy(() => ChatCompletionChunkUsage$outboundSchema))
      .optional(),
  }).transform((v) => {
    return remap$(v, {
      systemFingerprint: "system_fingerprint",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Data$ {
  /** @deprecated use `Data$inboundSchema` instead. */
  export const inboundSchema = Data$inboundSchema;
  /** @deprecated use `Data$outboundSchema` instead. */
  export const outboundSchema = Data$outboundSchema;
  /** @deprecated use `Data$Outbound` instead. */
  export type Outbound = Data$Outbound;
}

export function dataToJSON(data: Data): string {
  return JSON.stringify(Data$outboundSchema.parse(data));
}

export function dataFromJSON(
  jsonString: string,
): SafeParseResult<Data, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Data$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Data' from JSON`,
  );
}

/** @internal */
export const ChatCompletionChunk$inboundSchema: z.ZodType<
  ChatCompletionChunk,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.string().transform((v, ctx) => {
    try {
      return JSON.parse(v);
    } catch (err) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message: `malformed json: ${err}`,
      });
      return z.NEVER;
    }
  }).pipe(z.lazy(() => Data$inboundSchema).optional()),
});

/** @internal */
export type ChatCompletionChunk$Outbound = {
  data?: Data$Outbound | undefined;
};

/** @internal */
export const ChatCompletionChunk$outboundSchema: z.ZodType<
  ChatCompletionChunk$Outbound,
  z.ZodTypeDef,
  ChatCompletionChunk
> = z.object({
  data: z.lazy(() => Data$outboundSchema).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ChatCompletionChunk$ {
  /** @deprecated use `ChatCompletionChunk$inboundSchema` instead. */
  export const inboundSchema = ChatCompletionChunk$inboundSchema;
  /** @deprecated use `ChatCompletionChunk$outboundSchema` instead. */
  export const outboundSchema = ChatCompletionChunk$outboundSchema;
  /** @deprecated use `ChatCompletionChunk$Outbound` instead. */
  export type Outbound = ChatCompletionChunk$Outbound;
}

export function chatCompletionChunkToJSON(
  chatCompletionChunk: ChatCompletionChunk,
): string {
  return JSON.stringify(
    ChatCompletionChunk$outboundSchema.parse(chatCompletionChunk),
  );
}

export function chatCompletionChunkFromJSON(
  jsonString: string,
): SafeParseResult<ChatCompletionChunk, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChatCompletionChunk$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChatCompletionChunk' from JSON`,
  );
}
