/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  ChatCompletion,
  ChatCompletion$inboundSchema,
} from "./chatcompletion.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type ChatCompletionList = {
  data: Array<ChatCompletion>;
  firstId: string;
  hasMore: boolean;
  lastId: string;
  object: string;
};

/** @internal */
export const ChatCompletionList$inboundSchema: z.ZodType<
  ChatCompletionList,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(ChatCompletion$inboundSchema),
  first_id: z.string(),
  has_more: z.boolean(),
  last_id: z.string(),
  object: z.string(),
}).transform((v) => {
  return remap$(v, {
    "first_id": "firstId",
    "has_more": "hasMore",
    "last_id": "lastId",
  });
});

export function chatCompletionListFromJSON(
  jsonString: string,
): SafeParseResult<ChatCompletionList, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChatCompletionList$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChatCompletionList' from JSON`,
  );
}
