/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  ChatCompletionChunkChoice,
  ChatCompletionChunkChoice$inboundSchema,
} from "./chatcompletionchunkchoice.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * The object type, which is always 'chat.completion.chunk'.
 */
export const ObjectT = {
  ChatCompletionChunk: "chat.completion.chunk",
} as const;
/**
 * The object type, which is always 'chat.completion.chunk'.
 */
export type ObjectT = ClosedEnum<typeof ObjectT>;

/**
 * Usage statistics for the completion request. When stream_options.include_usage is set, the final chunk before [DONE] will contain the full usage statistics, and all other chunks will include usage with a null value.
 */
export type ChatCompletionChunkUsage = {
  completionTokens: number;
  completionTokensDetails?: any | undefined;
  promptTokens: number;
  promptTokensDetails?: any | undefined;
  totalTokens: number;
};

export type ChatCompletionChunkData = {
  /**
   * A unique identifier for the chat completion.
   */
  id: string;
  /**
   * The object type, which is always 'chat.completion.chunk'.
   */
  object: ObjectT;
  /**
   * The Unix timestamp (in seconds) of when the chat completion was created.
   */
  created: number;
  /**
   * The model used for the chat completion.
   */
  model: string;
  /**
   * This fingerprint represents the backend configuration that the model runs with.
   */
  systemFingerprint?: string | null | undefined;
  /**
   * A list of chat completion choices.
   */
  choices: Array<ChatCompletionChunkChoice>;
  /**
   * Usage statistics for the completion request. When stream_options.include_usage is set, the final chunk before [DONE] will contain the full usage statistics, and all other chunks will include usage with a null value.
   */
  usage?: ChatCompletionChunkUsage | null | undefined;
};

export type ChatCompletionChunk = {
  data?: ChatCompletionChunkData | undefined;
};

/** @internal */
export const ObjectT$inboundSchema: z.ZodNativeEnum<typeof ObjectT> = z
  .nativeEnum(ObjectT);

/** @internal */
export const ChatCompletionChunkUsage$inboundSchema: z.ZodType<
  ChatCompletionChunkUsage,
  z.ZodTypeDef,
  unknown
> = z.object({
  completion_tokens: z.number().int(),
  completion_tokens_details: z.any().optional(),
  prompt_tokens: z.number().int(),
  prompt_tokens_details: z.any().optional(),
  total_tokens: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    "completion_tokens": "completionTokens",
    "completion_tokens_details": "completionTokensDetails",
    "prompt_tokens": "promptTokens",
    "prompt_tokens_details": "promptTokensDetails",
    "total_tokens": "totalTokens",
  });
});

export function chatCompletionChunkUsageFromJSON(
  jsonString: string,
): SafeParseResult<ChatCompletionChunkUsage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChatCompletionChunkUsage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChatCompletionChunkUsage' from JSON`,
  );
}

/** @internal */
export const ChatCompletionChunkData$inboundSchema: z.ZodType<
  ChatCompletionChunkData,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  object: ObjectT$inboundSchema,
  created: z.number().int(),
  model: z.string(),
  system_fingerprint: z.nullable(z.string()).optional(),
  choices: z.array(ChatCompletionChunkChoice$inboundSchema),
  usage: z.nullable(z.lazy(() => ChatCompletionChunkUsage$inboundSchema))
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "system_fingerprint": "systemFingerprint",
  });
});

export function chatCompletionChunkDataFromJSON(
  jsonString: string,
): SafeParseResult<ChatCompletionChunkData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChatCompletionChunkData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChatCompletionChunkData' from JSON`,
  );
}

/** @internal */
export const ChatCompletionChunk$inboundSchema: z.ZodType<
  ChatCompletionChunk,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.string().transform((v, ctx) => {
    try {
      return JSON.parse(v);
    } catch (err) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message: `malformed json: ${err}`,
      });
      return z.NEVER;
    }
  }).pipe(z.lazy(() => ChatCompletionChunkData$inboundSchema).optional()),
});

export function chatCompletionChunkFromJSON(
  jsonString: string,
): SafeParseResult<ChatCompletionChunk, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChatCompletionChunk$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChatCompletionChunk' from JSON`,
  );
}
