/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { Choice, Choice$inboundSchema } from "./choice.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { Usage, Usage$inboundSchema } from "./usage.js";

export type ChatCompletion = {
  choices: Array<Choice>;
  created: number;
  id: string;
  model: string;
  object: string;
  serviceTier?: string | null | undefined;
  systemFingerprint?: string | null | undefined;
  usage: Usage;
  /**
   * Developer-defined metadata attached to the completion.
   */
  metadata?: { [k: string]: string } | null | undefined;
};

/** @internal */
export const ChatCompletion$inboundSchema: z.ZodType<
  ChatCompletion,
  z.ZodTypeDef,
  unknown
> = z.object({
  choices: z.array(Choice$inboundSchema),
  created: z.number().int(),
  id: z.string(),
  model: z.string(),
  object: z.string(),
  service_tier: z.nullable(z.string()).optional(),
  system_fingerprint: z.nullable(z.string()).optional(),
  usage: Usage$inboundSchema,
  metadata: z.nullable(z.record(z.string())).optional(),
}).transform((v) => {
  return remap$(v, {
    "service_tier": "serviceTier",
    "system_fingerprint": "systemFingerprint",
  });
});

export function chatCompletionFromJSON(
  jsonString: string,
): SafeParseResult<ChatCompletion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChatCompletion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChatCompletion' from JSON`,
  );
}
