/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  MessageResponse,
  MessageResponse$inboundSchema,
} from "./messageresponse.js";

export type Choice = {
  finishReason: string;
  index: number;
  logprobs?: any | undefined;
  message: MessageResponse;
};

/** @internal */
export const Choice$inboundSchema: z.ZodType<Choice, z.ZodTypeDef, unknown> = z
  .object({
    finish_reason: z.string(),
    index: z.number().int(),
    logprobs: z.any().optional(),
    message: MessageResponse$inboundSchema,
  }).transform((v) => {
    return remap$(v, {
      "finish_reason": "finishReason",
    });
  });

export function choiceFromJSON(
  jsonString: string,
): SafeParseResult<Choice, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Choice$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Choice' from JSON`,
  );
}
