/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type FunctionT = {
  description?: string | null | undefined;
  name: string;
  parameters?: any | undefined;
  strict?: boolean | null | undefined;
};

/** @internal */
export type FunctionT$Outbound = {
  description?: string | null | undefined;
  name: string;
  parameters?: any | undefined;
  strict?: boolean | null | undefined;
};

/** @internal */
export const FunctionT$outboundSchema: z.ZodType<
  FunctionT$Outbound,
  z.ZodTypeDef,
  FunctionT
> = z.object({
  description: z.nullable(z.string()).optional(),
  name: z.string(),
  parameters: z.any().optional(),
  strict: z.nullable(z.boolean()).optional(),
});

export function functionToJSON(functionT: FunctionT): string {
  return JSON.stringify(FunctionT$outboundSchema.parse(functionT));
}
