/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type ImageData = {
  /**
   * The base64-encoded JSON of the generated image, if response_format is b64_json.
   */
  b64Json?: string | null | undefined;
  /**
   * The prompt that was used to generate the image, if there was any revision to the prompt.
   */
  revisedPrompt?: string | null | undefined;
  /**
   * The URL of the generated image, if response_format is url (default).
   */
  url?: string | null | undefined;
};

/** @internal */
export const ImageData$inboundSchema: z.ZodType<
  ImageData,
  z.ZodTypeDef,
  unknown
> = z.object({
  b64_json: z.nullable(z.string()).optional(),
  revised_prompt: z.nullable(z.string()).optional(),
  url: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "b64_json": "b64Json",
    "revised_prompt": "revisedPrompt",
  });
});

/** @internal */
export type ImageData$Outbound = {
  b64_json?: string | null | undefined;
  revised_prompt?: string | null | undefined;
  url?: string | null | undefined;
};

/** @internal */
export const ImageData$outboundSchema: z.ZodType<
  ImageData$Outbound,
  z.ZodTypeDef,
  ImageData
> = z.object({
  b64Json: z.nullable(z.string()).optional(),
  revisedPrompt: z.nullable(z.string()).optional(),
  url: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    b64Json: "b64_json",
    revisedPrompt: "revised_prompt",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ImageData$ {
  /** @deprecated use `ImageData$inboundSchema` instead. */
  export const inboundSchema = ImageData$inboundSchema;
  /** @deprecated use `ImageData$outboundSchema` instead. */
  export const outboundSchema = ImageData$outboundSchema;
  /** @deprecated use `ImageData$Outbound` instead. */
  export type Outbound = ImageData$Outbound;
}

export function imageDataToJSON(imageData: ImageData): string {
  return JSON.stringify(ImageData$outboundSchema.parse(imageData));
}

export function imageDataFromJSON(
  jsonString: string,
): SafeParseResult<ImageData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ImageData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ImageData' from JSON`,
  );
}
