/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type ImageData = {
  /**
   * The base64-encoded JSON of the generated image, if response_format is b64_json.
   */
  b64Json?: string | null | undefined;
  /**
   * The prompt that was used to generate the image, if there was any revision to the prompt.
   */
  revisedPrompt?: string | null | undefined;
  /**
   * The URL of the generated image, if response_format is url (default).
   */
  url?: string | null | undefined;
};

/** @internal */
export const ImageData$inboundSchema: z.ZodType<
  ImageData,
  z.ZodTypeDef,
  unknown
> = z.object({
  b64_json: z.nullable(z.string()).optional(),
  revised_prompt: z.nullable(z.string()).optional(),
  url: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "b64_json": "b64Json",
    "revised_prompt": "revisedPrompt",
  });
});

export function imageDataFromJSON(
  jsonString: string,
): SafeParseResult<ImageData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ImageData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ImageData' from JSON`,
  );
}
