/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  ImageInputTokens,
  ImageInputTokens$inboundSchema,
} from "./imageinputtokens.js";

export type ImageUsage = {
  /**
   * Number of tokens in the input prompt.
   */
  inputTokens: number;
  inputTokensDetails: ImageInputTokens;
  /**
   * Number of tokens used for the generated image.
   */
  outputTokens: number;
  /**
   * Total number of tokens used in the request (input + output).
   */
  totalTokens: number;
};

/** @internal */
export const ImageUsage$inboundSchema: z.ZodType<
  ImageUsage,
  z.ZodTypeDef,
  unknown
> = z.object({
  input_tokens: z.number().int(),
  input_tokens_details: ImageInputTokens$inboundSchema,
  output_tokens: z.number().int(),
  total_tokens: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    "input_tokens": "inputTokens",
    "input_tokens_details": "inputTokensDetails",
    "output_tokens": "outputTokens",
    "total_tokens": "totalTokens",
  });
});

export function imageUsageFromJSON(
  jsonString: string,
): SafeParseResult<ImageUsage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ImageUsage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ImageUsage' from JSON`,
  );
}
