/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type ImageInputTokens = {
  /**
   * Number of tokens used for image processing.
   */
  imageTokens: number;
  /**
   * Number of tokens used for text processing.
   */
  textTokens: number;
};

/** @internal */
export const ImageInputTokens$inboundSchema: z.ZodType<
  ImageInputTokens,
  z.ZodTypeDef,
  unknown
> = z.object({
  image_tokens: z.number().int(),
  text_tokens: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    "image_tokens": "imageTokens",
    "text_tokens": "textTokens",
  });
});

export function imageInputTokensFromJSON(
  jsonString: string,
): SafeParseResult<ImageInputTokens, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ImageInputTokens$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ImageInputTokens' from JSON`,
  );
}
