/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  ItemUnion,
  ItemUnion$Outbound,
  ItemUnion$outboundSchema,
} from "./itemunion.js";
import {
  MessageContent,
  MessageContent$Outbound,
  MessageContent$outboundSchema,
} from "./messagecontent.js";

export type InputItem2 = {
  id: string;
  type?: string | null | undefined;
};

export type InputItem1 = {
  content: MessageContent;
  role: string;
};

export type InputItemUnion = InputItem1 | InputItem2 | ItemUnion;

/** @internal */
export type InputItem2$Outbound = {
  id: string;
  type?: string | null | undefined;
};

/** @internal */
export const InputItem2$outboundSchema: z.ZodType<
  InputItem2$Outbound,
  z.ZodTypeDef,
  InputItem2
> = z.object({
  id: z.string(),
  type: z.nullable(z.string()).optional(),
});

export function inputItem2ToJSON(inputItem2: InputItem2): string {
  return JSON.stringify(InputItem2$outboundSchema.parse(inputItem2));
}

/** @internal */
export type InputItem1$Outbound = {
  content: MessageContent$Outbound;
  role: string;
};

/** @internal */
export const InputItem1$outboundSchema: z.ZodType<
  InputItem1$Outbound,
  z.ZodTypeDef,
  InputItem1
> = z.object({
  content: MessageContent$outboundSchema,
  role: z.string(),
});

export function inputItem1ToJSON(inputItem1: InputItem1): string {
  return JSON.stringify(InputItem1$outboundSchema.parse(inputItem1));
}

/** @internal */
export type InputItemUnion$Outbound =
  | InputItem1$Outbound
  | InputItem2$Outbound
  | ItemUnion$Outbound;

/** @internal */
export const InputItemUnion$outboundSchema: z.ZodType<
  InputItemUnion$Outbound,
  z.ZodTypeDef,
  InputItemUnion
> = z.union([
  z.lazy(() => InputItem1$outboundSchema),
  z.lazy(() => InputItem2$outboundSchema),
  ItemUnion$outboundSchema,
]);

export function inputItemUnionToJSON(inputItemUnion: InputItemUnion): string {
  return JSON.stringify(InputItemUnion$outboundSchema.parse(inputItemUnion));
}
