/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  MessageContent,
  MessageContent$inboundSchema,
  MessageContent$Outbound,
  MessageContent$outboundSchema,
} from "./messagecontent.js";
import {
  OutputMessage,
  OutputMessage$inboundSchema,
  OutputMessage$Outbound,
  OutputMessage$outboundSchema,
} from "./outputmessage.js";
import {
  ToolCallOutput,
  ToolCallOutput$inboundSchema,
  ToolCallOutput$Outbound,
  ToolCallOutput$outboundSchema,
} from "./toolcalloutput.js";

export type Item19 = {
  callId: string;
  id?: string | null | undefined;
  input: string;
  name: string;
  type: string;
};

export type Item18 = {
  callId: string;
  id?: string | null | undefined;
  output: ToolCallOutput;
  type: string;
};

export type Item17 = {
  approvalRequestId?: string | null | undefined;
  arguments: string;
  error?: string | null | undefined;
  id: string;
  name: string;
  output?: string | null | undefined;
  serverLabel: string;
  status?: string | null | undefined;
  type: string;
};

export type Item16 = {
  approvalRequestId: string;
  approve: boolean;
  id?: string | null | undefined;
  reason?: string | null | undefined;
  type: string;
};

export type Item15 = {
  arguments: string;
  id: string;
  name: string;
  serverLabel: string;
  type: string;
};

export type Item14 = {
  error?: string | null | undefined;
  id: string;
  serverLabel: string;
  tools: Array<any>;
  type: string;
};

export type Item13 = {
  id: string;
  output: string;
  status?: string | null | undefined;
  type: string;
};

export type Item12 = {
  action?: any | undefined;
  callId: string;
  id: string;
  status: string;
  type: string;
};

export type Item11 = {
  code: string;
  containerId: string;
  id: string;
  outputs: Array<any>;
  status: string;
  type: string;
};

export type Item10 = {
  id: string;
  result: string;
  status: string;
  type: string;
};

export type Item9 = {
  content: Array<any>;
  encryptedContent?: string | null | undefined;
  id: string;
  status?: string | null | undefined;
  summary: Array<any>;
  type: string;
};

export type Item8 = {
  callId: string;
  id?: string | null | undefined;
  output: ToolCallOutput;
  status?: string | null | undefined;
  type: string;
};

export type Item7 = {
  arguments: string;
  callId: string;
  id?: string | null | undefined;
  name: string;
  status?: string | null | undefined;
  type: string;
};

export type Item6 = {
  action?: any | undefined;
  id: string;
  status: string;
  type: string;
};

export type Item5 = {
  acknowledgedSafetyChecks?: Array<any> | null | undefined;
  callId: string;
  id?: string | null | undefined;
  output?: any | undefined;
  status?: string | null | undefined;
  type: string;
};

export type Item4 = {
  action?: any | undefined;
  callId: string;
  id: string;
  pendingSafetyChecks: Array<any>;
  status: string;
  type: string;
};

export type Item3 = {
  id: string;
  queries: Array<any>;
  results: Array<any>;
  status: string;
  type: string;
};

export type Item2 = {
  content: Array<OutputMessage>;
  id: string;
  role: string;
  status: string;
  type: string;
};

export type Item1 = {
  content: MessageContent;
  role: string;
  status: string;
  type: string;
};

export type ItemUnion =
  | Item4
  | Item11
  | Item2
  | Item3
  | Item12
  | Item15
  | Item17
  | Item1
  | Item6
  | Item7
  | Item9
  | Item10
  | Item14
  | Item19
  | Item5
  | Item8
  | Item13
  | Item16
  | Item18;

/** @internal */
export const Item19$inboundSchema: z.ZodType<Item19, z.ZodTypeDef, unknown> = z
  .object({
    call_id: z.string(),
    id: z.nullable(z.string()).optional(),
    input: z.string(),
    name: z.string(),
    type: z.string(),
  }).transform((v) => {
    return remap$(v, {
      "call_id": "callId",
    });
  });
/** @internal */
export type Item19$Outbound = {
  call_id: string;
  id?: string | null | undefined;
  input: string;
  name: string;
  type: string;
};

/** @internal */
export const Item19$outboundSchema: z.ZodType<
  Item19$Outbound,
  z.ZodTypeDef,
  Item19
> = z.object({
  callId: z.string(),
  id: z.nullable(z.string()).optional(),
  input: z.string(),
  name: z.string(),
  type: z.string(),
}).transform((v) => {
  return remap$(v, {
    callId: "call_id",
  });
});

export function item19ToJSON(item19: Item19): string {
  return JSON.stringify(Item19$outboundSchema.parse(item19));
}
export function item19FromJSON(
  jsonString: string,
): SafeParseResult<Item19, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Item19$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Item19' from JSON`,
  );
}

/** @internal */
export const Item18$inboundSchema: z.ZodType<Item18, z.ZodTypeDef, unknown> = z
  .object({
    call_id: z.string(),
    id: z.nullable(z.string()).optional(),
    output: ToolCallOutput$inboundSchema,
    type: z.string(),
  }).transform((v) => {
    return remap$(v, {
      "call_id": "callId",
    });
  });
/** @internal */
export type Item18$Outbound = {
  call_id: string;
  id?: string | null | undefined;
  output: ToolCallOutput$Outbound;
  type: string;
};

/** @internal */
export const Item18$outboundSchema: z.ZodType<
  Item18$Outbound,
  z.ZodTypeDef,
  Item18
> = z.object({
  callId: z.string(),
  id: z.nullable(z.string()).optional(),
  output: ToolCallOutput$outboundSchema,
  type: z.string(),
}).transform((v) => {
  return remap$(v, {
    callId: "call_id",
  });
});

export function item18ToJSON(item18: Item18): string {
  return JSON.stringify(Item18$outboundSchema.parse(item18));
}
export function item18FromJSON(
  jsonString: string,
): SafeParseResult<Item18, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Item18$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Item18' from JSON`,
  );
}

/** @internal */
export const Item17$inboundSchema: z.ZodType<Item17, z.ZodTypeDef, unknown> = z
  .object({
    approval_request_id: z.nullable(z.string()).optional(),
    arguments: z.string(),
    error: z.nullable(z.string()).optional(),
    id: z.string(),
    name: z.string(),
    output: z.nullable(z.string()).optional(),
    server_label: z.string(),
    status: z.nullable(z.string()).optional(),
    type: z.string(),
  }).transform((v) => {
    return remap$(v, {
      "approval_request_id": "approvalRequestId",
      "server_label": "serverLabel",
    });
  });
/** @internal */
export type Item17$Outbound = {
  approval_request_id?: string | null | undefined;
  arguments: string;
  error?: string | null | undefined;
  id: string;
  name: string;
  output?: string | null | undefined;
  server_label: string;
  status?: string | null | undefined;
  type: string;
};

/** @internal */
export const Item17$outboundSchema: z.ZodType<
  Item17$Outbound,
  z.ZodTypeDef,
  Item17
> = z.object({
  approvalRequestId: z.nullable(z.string()).optional(),
  arguments: z.string(),
  error: z.nullable(z.string()).optional(),
  id: z.string(),
  name: z.string(),
  output: z.nullable(z.string()).optional(),
  serverLabel: z.string(),
  status: z.nullable(z.string()).optional(),
  type: z.string(),
}).transform((v) => {
  return remap$(v, {
    approvalRequestId: "approval_request_id",
    serverLabel: "server_label",
  });
});

export function item17ToJSON(item17: Item17): string {
  return JSON.stringify(Item17$outboundSchema.parse(item17));
}
export function item17FromJSON(
  jsonString: string,
): SafeParseResult<Item17, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Item17$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Item17' from JSON`,
  );
}

/** @internal */
export const Item16$inboundSchema: z.ZodType<Item16, z.ZodTypeDef, unknown> = z
  .object({
    approval_request_id: z.string(),
    approve: z.boolean(),
    id: z.nullable(z.string()).optional(),
    reason: z.nullable(z.string()).optional(),
    type: z.string(),
  }).transform((v) => {
    return remap$(v, {
      "approval_request_id": "approvalRequestId",
    });
  });
/** @internal */
export type Item16$Outbound = {
  approval_request_id: string;
  approve: boolean;
  id?: string | null | undefined;
  reason?: string | null | undefined;
  type: string;
};

/** @internal */
export const Item16$outboundSchema: z.ZodType<
  Item16$Outbound,
  z.ZodTypeDef,
  Item16
> = z.object({
  approvalRequestId: z.string(),
  approve: z.boolean(),
  id: z.nullable(z.string()).optional(),
  reason: z.nullable(z.string()).optional(),
  type: z.string(),
}).transform((v) => {
  return remap$(v, {
    approvalRequestId: "approval_request_id",
  });
});

export function item16ToJSON(item16: Item16): string {
  return JSON.stringify(Item16$outboundSchema.parse(item16));
}
export function item16FromJSON(
  jsonString: string,
): SafeParseResult<Item16, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Item16$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Item16' from JSON`,
  );
}

/** @internal */
export const Item15$inboundSchema: z.ZodType<Item15, z.ZodTypeDef, unknown> = z
  .object({
    arguments: z.string(),
    id: z.string(),
    name: z.string(),
    server_label: z.string(),
    type: z.string(),
  }).transform((v) => {
    return remap$(v, {
      "server_label": "serverLabel",
    });
  });
/** @internal */
export type Item15$Outbound = {
  arguments: string;
  id: string;
  name: string;
  server_label: string;
  type: string;
};

/** @internal */
export const Item15$outboundSchema: z.ZodType<
  Item15$Outbound,
  z.ZodTypeDef,
  Item15
> = z.object({
  arguments: z.string(),
  id: z.string(),
  name: z.string(),
  serverLabel: z.string(),
  type: z.string(),
}).transform((v) => {
  return remap$(v, {
    serverLabel: "server_label",
  });
});

export function item15ToJSON(item15: Item15): string {
  return JSON.stringify(Item15$outboundSchema.parse(item15));
}
export function item15FromJSON(
  jsonString: string,
): SafeParseResult<Item15, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Item15$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Item15' from JSON`,
  );
}

/** @internal */
export const Item14$inboundSchema: z.ZodType<Item14, z.ZodTypeDef, unknown> = z
  .object({
    error: z.nullable(z.string()).optional(),
    id: z.string(),
    server_label: z.string(),
    tools: z.array(z.any()),
    type: z.string(),
  }).transform((v) => {
    return remap$(v, {
      "server_label": "serverLabel",
    });
  });
/** @internal */
export type Item14$Outbound = {
  error?: string | null | undefined;
  id: string;
  server_label: string;
  tools: Array<any>;
  type: string;
};

/** @internal */
export const Item14$outboundSchema: z.ZodType<
  Item14$Outbound,
  z.ZodTypeDef,
  Item14
> = z.object({
  error: z.nullable(z.string()).optional(),
  id: z.string(),
  serverLabel: z.string(),
  tools: z.array(z.any()),
  type: z.string(),
}).transform((v) => {
  return remap$(v, {
    serverLabel: "server_label",
  });
});

export function item14ToJSON(item14: Item14): string {
  return JSON.stringify(Item14$outboundSchema.parse(item14));
}
export function item14FromJSON(
  jsonString: string,
): SafeParseResult<Item14, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Item14$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Item14' from JSON`,
  );
}

/** @internal */
export const Item13$inboundSchema: z.ZodType<Item13, z.ZodTypeDef, unknown> = z
  .object({
    id: z.string(),
    output: z.string(),
    status: z.nullable(z.string()).optional(),
    type: z.string(),
  });
/** @internal */
export type Item13$Outbound = {
  id: string;
  output: string;
  status?: string | null | undefined;
  type: string;
};

/** @internal */
export const Item13$outboundSchema: z.ZodType<
  Item13$Outbound,
  z.ZodTypeDef,
  Item13
> = z.object({
  id: z.string(),
  output: z.string(),
  status: z.nullable(z.string()).optional(),
  type: z.string(),
});

export function item13ToJSON(item13: Item13): string {
  return JSON.stringify(Item13$outboundSchema.parse(item13));
}
export function item13FromJSON(
  jsonString: string,
): SafeParseResult<Item13, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Item13$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Item13' from JSON`,
  );
}

/** @internal */
export const Item12$inboundSchema: z.ZodType<Item12, z.ZodTypeDef, unknown> = z
  .object({
    action: z.any().optional(),
    call_id: z.string(),
    id: z.string(),
    status: z.string(),
    type: z.string(),
  }).transform((v) => {
    return remap$(v, {
      "call_id": "callId",
    });
  });
/** @internal */
export type Item12$Outbound = {
  action?: any | undefined;
  call_id: string;
  id: string;
  status: string;
  type: string;
};

/** @internal */
export const Item12$outboundSchema: z.ZodType<
  Item12$Outbound,
  z.ZodTypeDef,
  Item12
> = z.object({
  action: z.any().optional(),
  callId: z.string(),
  id: z.string(),
  status: z.string(),
  type: z.string(),
}).transform((v) => {
  return remap$(v, {
    callId: "call_id",
  });
});

export function item12ToJSON(item12: Item12): string {
  return JSON.stringify(Item12$outboundSchema.parse(item12));
}
export function item12FromJSON(
  jsonString: string,
): SafeParseResult<Item12, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Item12$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Item12' from JSON`,
  );
}

/** @internal */
export const Item11$inboundSchema: z.ZodType<Item11, z.ZodTypeDef, unknown> = z
  .object({
    code: z.string(),
    container_id: z.string(),
    id: z.string(),
    outputs: z.array(z.any()),
    status: z.string(),
    type: z.string(),
  }).transform((v) => {
    return remap$(v, {
      "container_id": "containerId",
    });
  });
/** @internal */
export type Item11$Outbound = {
  code: string;
  container_id: string;
  id: string;
  outputs: Array<any>;
  status: string;
  type: string;
};

/** @internal */
export const Item11$outboundSchema: z.ZodType<
  Item11$Outbound,
  z.ZodTypeDef,
  Item11
> = z.object({
  code: z.string(),
  containerId: z.string(),
  id: z.string(),
  outputs: z.array(z.any()),
  status: z.string(),
  type: z.string(),
}).transform((v) => {
  return remap$(v, {
    containerId: "container_id",
  });
});

export function item11ToJSON(item11: Item11): string {
  return JSON.stringify(Item11$outboundSchema.parse(item11));
}
export function item11FromJSON(
  jsonString: string,
): SafeParseResult<Item11, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Item11$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Item11' from JSON`,
  );
}

/** @internal */
export const Item10$inboundSchema: z.ZodType<Item10, z.ZodTypeDef, unknown> = z
  .object({
    id: z.string(),
    result: z.string(),
    status: z.string(),
    type: z.string(),
  });
/** @internal */
export type Item10$Outbound = {
  id: string;
  result: string;
  status: string;
  type: string;
};

/** @internal */
export const Item10$outboundSchema: z.ZodType<
  Item10$Outbound,
  z.ZodTypeDef,
  Item10
> = z.object({
  id: z.string(),
  result: z.string(),
  status: z.string(),
  type: z.string(),
});

export function item10ToJSON(item10: Item10): string {
  return JSON.stringify(Item10$outboundSchema.parse(item10));
}
export function item10FromJSON(
  jsonString: string,
): SafeParseResult<Item10, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Item10$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Item10' from JSON`,
  );
}

/** @internal */
export const Item9$inboundSchema: z.ZodType<Item9, z.ZodTypeDef, unknown> = z
  .object({
    content: z.array(z.any()),
    encrypted_content: z.nullable(z.string()).optional(),
    id: z.string(),
    status: z.nullable(z.string()).optional(),
    summary: z.array(z.any()),
    type: z.string(),
  }).transform((v) => {
    return remap$(v, {
      "encrypted_content": "encryptedContent",
    });
  });
/** @internal */
export type Item9$Outbound = {
  content: Array<any>;
  encrypted_content?: string | null | undefined;
  id: string;
  status?: string | null | undefined;
  summary: Array<any>;
  type: string;
};

/** @internal */
export const Item9$outboundSchema: z.ZodType<
  Item9$Outbound,
  z.ZodTypeDef,
  Item9
> = z.object({
  content: z.array(z.any()),
  encryptedContent: z.nullable(z.string()).optional(),
  id: z.string(),
  status: z.nullable(z.string()).optional(),
  summary: z.array(z.any()),
  type: z.string(),
}).transform((v) => {
  return remap$(v, {
    encryptedContent: "encrypted_content",
  });
});

export function item9ToJSON(item9: Item9): string {
  return JSON.stringify(Item9$outboundSchema.parse(item9));
}
export function item9FromJSON(
  jsonString: string,
): SafeParseResult<Item9, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Item9$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Item9' from JSON`,
  );
}

/** @internal */
export const Item8$inboundSchema: z.ZodType<Item8, z.ZodTypeDef, unknown> = z
  .object({
    call_id: z.string(),
    id: z.nullable(z.string()).optional(),
    output: ToolCallOutput$inboundSchema,
    status: z.nullable(z.string()).optional(),
    type: z.string(),
  }).transform((v) => {
    return remap$(v, {
      "call_id": "callId",
    });
  });
/** @internal */
export type Item8$Outbound = {
  call_id: string;
  id?: string | null | undefined;
  output: ToolCallOutput$Outbound;
  status?: string | null | undefined;
  type: string;
};

/** @internal */
export const Item8$outboundSchema: z.ZodType<
  Item8$Outbound,
  z.ZodTypeDef,
  Item8
> = z.object({
  callId: z.string(),
  id: z.nullable(z.string()).optional(),
  output: ToolCallOutput$outboundSchema,
  status: z.nullable(z.string()).optional(),
  type: z.string(),
}).transform((v) => {
  return remap$(v, {
    callId: "call_id",
  });
});

export function item8ToJSON(item8: Item8): string {
  return JSON.stringify(Item8$outboundSchema.parse(item8));
}
export function item8FromJSON(
  jsonString: string,
): SafeParseResult<Item8, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Item8$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Item8' from JSON`,
  );
}

/** @internal */
export const Item7$inboundSchema: z.ZodType<Item7, z.ZodTypeDef, unknown> = z
  .object({
    arguments: z.string(),
    call_id: z.string(),
    id: z.nullable(z.string()).optional(),
    name: z.string(),
    status: z.nullable(z.string()).optional(),
    type: z.string(),
  }).transform((v) => {
    return remap$(v, {
      "call_id": "callId",
    });
  });
/** @internal */
export type Item7$Outbound = {
  arguments: string;
  call_id: string;
  id?: string | null | undefined;
  name: string;
  status?: string | null | undefined;
  type: string;
};

/** @internal */
export const Item7$outboundSchema: z.ZodType<
  Item7$Outbound,
  z.ZodTypeDef,
  Item7
> = z.object({
  arguments: z.string(),
  callId: z.string(),
  id: z.nullable(z.string()).optional(),
  name: z.string(),
  status: z.nullable(z.string()).optional(),
  type: z.string(),
}).transform((v) => {
  return remap$(v, {
    callId: "call_id",
  });
});

export function item7ToJSON(item7: Item7): string {
  return JSON.stringify(Item7$outboundSchema.parse(item7));
}
export function item7FromJSON(
  jsonString: string,
): SafeParseResult<Item7, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Item7$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Item7' from JSON`,
  );
}

/** @internal */
export const Item6$inboundSchema: z.ZodType<Item6, z.ZodTypeDef, unknown> = z
  .object({
    action: z.any().optional(),
    id: z.string(),
    status: z.string(),
    type: z.string(),
  });
/** @internal */
export type Item6$Outbound = {
  action?: any | undefined;
  id: string;
  status: string;
  type: string;
};

/** @internal */
export const Item6$outboundSchema: z.ZodType<
  Item6$Outbound,
  z.ZodTypeDef,
  Item6
> = z.object({
  action: z.any().optional(),
  id: z.string(),
  status: z.string(),
  type: z.string(),
});

export function item6ToJSON(item6: Item6): string {
  return JSON.stringify(Item6$outboundSchema.parse(item6));
}
export function item6FromJSON(
  jsonString: string,
): SafeParseResult<Item6, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Item6$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Item6' from JSON`,
  );
}

/** @internal */
export const Item5$inboundSchema: z.ZodType<Item5, z.ZodTypeDef, unknown> = z
  .object({
    acknowledged_safety_checks: z.nullable(z.array(z.any())).optional(),
    call_id: z.string(),
    id: z.nullable(z.string()).optional(),
    output: z.any().optional(),
    status: z.nullable(z.string()).optional(),
    type: z.string(),
  }).transform((v) => {
    return remap$(v, {
      "acknowledged_safety_checks": "acknowledgedSafetyChecks",
      "call_id": "callId",
    });
  });
/** @internal */
export type Item5$Outbound = {
  acknowledged_safety_checks?: Array<any> | null | undefined;
  call_id: string;
  id?: string | null | undefined;
  output?: any | undefined;
  status?: string | null | undefined;
  type: string;
};

/** @internal */
export const Item5$outboundSchema: z.ZodType<
  Item5$Outbound,
  z.ZodTypeDef,
  Item5
> = z.object({
  acknowledgedSafetyChecks: z.nullable(z.array(z.any())).optional(),
  callId: z.string(),
  id: z.nullable(z.string()).optional(),
  output: z.any().optional(),
  status: z.nullable(z.string()).optional(),
  type: z.string(),
}).transform((v) => {
  return remap$(v, {
    acknowledgedSafetyChecks: "acknowledged_safety_checks",
    callId: "call_id",
  });
});

export function item5ToJSON(item5: Item5): string {
  return JSON.stringify(Item5$outboundSchema.parse(item5));
}
export function item5FromJSON(
  jsonString: string,
): SafeParseResult<Item5, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Item5$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Item5' from JSON`,
  );
}

/** @internal */
export const Item4$inboundSchema: z.ZodType<Item4, z.ZodTypeDef, unknown> = z
  .object({
    action: z.any().optional(),
    call_id: z.string(),
    id: z.string(),
    pending_safety_checks: z.array(z.any()),
    status: z.string(),
    type: z.string(),
  }).transform((v) => {
    return remap$(v, {
      "call_id": "callId",
      "pending_safety_checks": "pendingSafetyChecks",
    });
  });
/** @internal */
export type Item4$Outbound = {
  action?: any | undefined;
  call_id: string;
  id: string;
  pending_safety_checks: Array<any>;
  status: string;
  type: string;
};

/** @internal */
export const Item4$outboundSchema: z.ZodType<
  Item4$Outbound,
  z.ZodTypeDef,
  Item4
> = z.object({
  action: z.any().optional(),
  callId: z.string(),
  id: z.string(),
  pendingSafetyChecks: z.array(z.any()),
  status: z.string(),
  type: z.string(),
}).transform((v) => {
  return remap$(v, {
    callId: "call_id",
    pendingSafetyChecks: "pending_safety_checks",
  });
});

export function item4ToJSON(item4: Item4): string {
  return JSON.stringify(Item4$outboundSchema.parse(item4));
}
export function item4FromJSON(
  jsonString: string,
): SafeParseResult<Item4, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Item4$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Item4' from JSON`,
  );
}

/** @internal */
export const Item3$inboundSchema: z.ZodType<Item3, z.ZodTypeDef, unknown> = z
  .object({
    id: z.string(),
    queries: z.array(z.any()),
    results: z.array(z.any()),
    status: z.string(),
    type: z.string(),
  });
/** @internal */
export type Item3$Outbound = {
  id: string;
  queries: Array<any>;
  results: Array<any>;
  status: string;
  type: string;
};

/** @internal */
export const Item3$outboundSchema: z.ZodType<
  Item3$Outbound,
  z.ZodTypeDef,
  Item3
> = z.object({
  id: z.string(),
  queries: z.array(z.any()),
  results: z.array(z.any()),
  status: z.string(),
  type: z.string(),
});

export function item3ToJSON(item3: Item3): string {
  return JSON.stringify(Item3$outboundSchema.parse(item3));
}
export function item3FromJSON(
  jsonString: string,
): SafeParseResult<Item3, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Item3$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Item3' from JSON`,
  );
}

/** @internal */
export const Item2$inboundSchema: z.ZodType<Item2, z.ZodTypeDef, unknown> = z
  .object({
    content: z.array(OutputMessage$inboundSchema),
    id: z.string(),
    role: z.string(),
    status: z.string(),
    type: z.string(),
  });
/** @internal */
export type Item2$Outbound = {
  content: Array<OutputMessage$Outbound>;
  id: string;
  role: string;
  status: string;
  type: string;
};

/** @internal */
export const Item2$outboundSchema: z.ZodType<
  Item2$Outbound,
  z.ZodTypeDef,
  Item2
> = z.object({
  content: z.array(OutputMessage$outboundSchema),
  id: z.string(),
  role: z.string(),
  status: z.string(),
  type: z.string(),
});

export function item2ToJSON(item2: Item2): string {
  return JSON.stringify(Item2$outboundSchema.parse(item2));
}
export function item2FromJSON(
  jsonString: string,
): SafeParseResult<Item2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Item2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Item2' from JSON`,
  );
}

/** @internal */
export const Item1$inboundSchema: z.ZodType<Item1, z.ZodTypeDef, unknown> = z
  .object({
    content: MessageContent$inboundSchema,
    role: z.string(),
    status: z.string(),
    type: z.string(),
  });
/** @internal */
export type Item1$Outbound = {
  content: MessageContent$Outbound;
  role: string;
  status: string;
  type: string;
};

/** @internal */
export const Item1$outboundSchema: z.ZodType<
  Item1$Outbound,
  z.ZodTypeDef,
  Item1
> = z.object({
  content: MessageContent$outboundSchema,
  role: z.string(),
  status: z.string(),
  type: z.string(),
});

export function item1ToJSON(item1: Item1): string {
  return JSON.stringify(Item1$outboundSchema.parse(item1));
}
export function item1FromJSON(
  jsonString: string,
): SafeParseResult<Item1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Item1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Item1' from JSON`,
  );
}

/** @internal */
export const ItemUnion$inboundSchema: z.ZodType<
  ItemUnion,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => Item4$inboundSchema),
  z.lazy(() => Item11$inboundSchema),
  z.lazy(() => Item2$inboundSchema),
  z.lazy(() => Item3$inboundSchema),
  z.lazy(() => Item12$inboundSchema),
  z.lazy(() => Item15$inboundSchema),
  z.lazy(() => Item17$inboundSchema),
  z.lazy(() => Item1$inboundSchema),
  z.lazy(() => Item6$inboundSchema),
  z.lazy(() => Item7$inboundSchema),
  z.lazy(() => Item9$inboundSchema),
  z.lazy(() => Item10$inboundSchema),
  z.lazy(() => Item14$inboundSchema),
  z.lazy(() => Item19$inboundSchema),
  z.lazy(() => Item5$inboundSchema),
  z.lazy(() => Item8$inboundSchema),
  z.lazy(() => Item13$inboundSchema),
  z.lazy(() => Item16$inboundSchema),
  z.lazy(() => Item18$inboundSchema),
]);
/** @internal */
export type ItemUnion$Outbound =
  | Item4$Outbound
  | Item11$Outbound
  | Item2$Outbound
  | Item3$Outbound
  | Item12$Outbound
  | Item15$Outbound
  | Item17$Outbound
  | Item1$Outbound
  | Item6$Outbound
  | Item7$Outbound
  | Item9$Outbound
  | Item10$Outbound
  | Item14$Outbound
  | Item19$Outbound
  | Item5$Outbound
  | Item8$Outbound
  | Item13$Outbound
  | Item16$Outbound
  | Item18$Outbound;

/** @internal */
export const ItemUnion$outboundSchema: z.ZodType<
  ItemUnion$Outbound,
  z.ZodTypeDef,
  ItemUnion
> = z.union([
  z.lazy(() => Item4$outboundSchema),
  z.lazy(() => Item11$outboundSchema),
  z.lazy(() => Item2$outboundSchema),
  z.lazy(() => Item3$outboundSchema),
  z.lazy(() => Item12$outboundSchema),
  z.lazy(() => Item15$outboundSchema),
  z.lazy(() => Item17$outboundSchema),
  z.lazy(() => Item1$outboundSchema),
  z.lazy(() => Item6$outboundSchema),
  z.lazy(() => Item7$outboundSchema),
  z.lazy(() => Item9$outboundSchema),
  z.lazy(() => Item10$outboundSchema),
  z.lazy(() => Item14$outboundSchema),
  z.lazy(() => Item19$outboundSchema),
  z.lazy(() => Item5$outboundSchema),
  z.lazy(() => Item8$outboundSchema),
  z.lazy(() => Item13$outboundSchema),
  z.lazy(() => Item16$outboundSchema),
  z.lazy(() => Item18$outboundSchema),
]);

export function itemUnionToJSON(itemUnion: ItemUnion): string {
  return JSON.stringify(ItemUnion$outboundSchema.parse(itemUnion));
}
export function itemUnionFromJSON(
  jsonString: string,
): SafeParseResult<ItemUnion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ItemUnion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ItemUnion' from JSON`,
  );
}
