/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  ContentPartUnion,
  ContentPartUnion$inboundSchema,
  ContentPartUnion$Outbound,
  ContentPartUnion$outboundSchema,
} from "./contentpartunion.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type MessageContent = string | Array<ContentPartUnion>;

/** @internal */
export const MessageContent$inboundSchema: z.ZodType<
  MessageContent,
  z.ZodTypeDef,
  unknown
> = z.union([z.string(), z.array(ContentPartUnion$inboundSchema)]);

/** @internal */
export type MessageContent$Outbound = string | Array<ContentPartUnion$Outbound>;

/** @internal */
export const MessageContent$outboundSchema: z.ZodType<
  MessageContent$Outbound,
  z.ZodTypeDef,
  MessageContent
> = z.union([z.string(), z.array(ContentPartUnion$outboundSchema)]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MessageContent$ {
  /** @deprecated use `MessageContent$inboundSchema` instead. */
  export const inboundSchema = MessageContent$inboundSchema;
  /** @deprecated use `MessageContent$outboundSchema` instead. */
  export const outboundSchema = MessageContent$outboundSchema;
  /** @deprecated use `MessageContent$Outbound` instead. */
  export type Outbound = MessageContent$Outbound;
}

export function messageContentToJSON(messageContent: MessageContent): string {
  return JSON.stringify(MessageContent$outboundSchema.parse(messageContent));
}

export function messageContentFromJSON(
  jsonString: string,
): SafeParseResult<MessageContent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MessageContent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MessageContent' from JSON`,
  );
}
