/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { ToolCall, ToolCall$inboundSchema } from "./toolcall.js";

export type MessageResponse = {
  annotations?: any | undefined;
  audio?: any | undefined;
  content?: string | null | undefined;
  refusal?: string | null | undefined;
  role: string;
  toolCalls?: Array<ToolCall> | null | undefined;
};

/** @internal */
export const MessageResponse$inboundSchema: z.ZodType<
  MessageResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  annotations: z.any().optional(),
  audio: z.any().optional(),
  content: z.nullable(z.string()).optional(),
  refusal: z.nullable(z.string()).optional(),
  role: z.string(),
  tool_calls: z.nullable(z.array(ToolCall$inboundSchema)).optional(),
}).transform((v) => {
  return remap$(v, {
    "tool_calls": "toolCalls",
  });
});

export function messageResponseFromJSON(
  jsonString: string,
): SafeParseResult<MessageResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MessageResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MessageResponse' from JSON`,
  );
}
