/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  ContentPartUnion,
  ContentPartUnion$inboundSchema,
  ContentPartUnion$Outbound,
  ContentPartUnion$outboundSchema,
} from "./contentpartunion.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type MessageContent = string | Array<ContentPartUnion>;

/** @internal */
export const MessageContent$inboundSchema: z.ZodType<
  MessageContent,
  z.ZodTypeDef,
  unknown
> = z.union([z.string(), z.array(ContentPartUnion$inboundSchema)]);
/** @internal */
export type MessageContent$Outbound = string | Array<ContentPartUnion$Outbound>;

/** @internal */
export const MessageContent$outboundSchema: z.ZodType<
  MessageContent$Outbound,
  z.ZodTypeDef,
  MessageContent
> = z.union([z.string(), z.array(ContentPartUnion$outboundSchema)]);

export function messageContentToJSON(messageContent: MessageContent): string {
  return JSON.stringify(MessageContent$outboundSchema.parse(messageContent));
}
export function messageContentFromJSON(
  jsonString: string,
): SafeParseResult<MessageContent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MessageContent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MessageContent' from JSON`,
  );
}
