/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const TypeRefusal = {
  Refusal: "refusal",
} as const;
export type TypeRefusal = ClosedEnum<typeof TypeRefusal>;

export type OutputMessageRefusal = {
  refusal: string;
  type: TypeRefusal;
};

export const TypeOutputText = {
  OutputText: "output_text",
} as const;
export type TypeOutputText = ClosedEnum<typeof TypeOutputText>;

export type OutputMessageOutputText = {
  annotations: Array<any>;
  logprobs?: Array<any> | null | undefined;
  text: string;
  type: TypeOutputText;
};

export type OutputMessage = OutputMessageOutputText | OutputMessageRefusal;

/** @internal */
export const TypeRefusal$inboundSchema: z.ZodNativeEnum<typeof TypeRefusal> = z
  .nativeEnum(TypeRefusal);
/** @internal */
export const TypeRefusal$outboundSchema: z.ZodNativeEnum<typeof TypeRefusal> =
  TypeRefusal$inboundSchema;

/** @internal */
export const OutputMessageRefusal$inboundSchema: z.ZodType<
  OutputMessageRefusal,
  z.ZodTypeDef,
  unknown
> = z.object({
  refusal: z.string(),
  type: TypeRefusal$inboundSchema,
});
/** @internal */
export type OutputMessageRefusal$Outbound = {
  refusal: string;
  type: string;
};

/** @internal */
export const OutputMessageRefusal$outboundSchema: z.ZodType<
  OutputMessageRefusal$Outbound,
  z.ZodTypeDef,
  OutputMessageRefusal
> = z.object({
  refusal: z.string(),
  type: TypeRefusal$outboundSchema,
});

export function outputMessageRefusalToJSON(
  outputMessageRefusal: OutputMessageRefusal,
): string {
  return JSON.stringify(
    OutputMessageRefusal$outboundSchema.parse(outputMessageRefusal),
  );
}
export function outputMessageRefusalFromJSON(
  jsonString: string,
): SafeParseResult<OutputMessageRefusal, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OutputMessageRefusal$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OutputMessageRefusal' from JSON`,
  );
}

/** @internal */
export const TypeOutputText$inboundSchema: z.ZodNativeEnum<
  typeof TypeOutputText
> = z.nativeEnum(TypeOutputText);
/** @internal */
export const TypeOutputText$outboundSchema: z.ZodNativeEnum<
  typeof TypeOutputText
> = TypeOutputText$inboundSchema;

/** @internal */
export const OutputMessageOutputText$inboundSchema: z.ZodType<
  OutputMessageOutputText,
  z.ZodTypeDef,
  unknown
> = z.object({
  annotations: z.array(z.any()),
  logprobs: z.nullable(z.array(z.any())).optional(),
  text: z.string(),
  type: TypeOutputText$inboundSchema,
});
/** @internal */
export type OutputMessageOutputText$Outbound = {
  annotations: Array<any>;
  logprobs?: Array<any> | null | undefined;
  text: string;
  type: string;
};

/** @internal */
export const OutputMessageOutputText$outboundSchema: z.ZodType<
  OutputMessageOutputText$Outbound,
  z.ZodTypeDef,
  OutputMessageOutputText
> = z.object({
  annotations: z.array(z.any()),
  logprobs: z.nullable(z.array(z.any())).optional(),
  text: z.string(),
  type: TypeOutputText$outboundSchema,
});

export function outputMessageOutputTextToJSON(
  outputMessageOutputText: OutputMessageOutputText,
): string {
  return JSON.stringify(
    OutputMessageOutputText$outboundSchema.parse(outputMessageOutputText),
  );
}
export function outputMessageOutputTextFromJSON(
  jsonString: string,
): SafeParseResult<OutputMessageOutputText, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OutputMessageOutputText$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OutputMessageOutputText' from JSON`,
  );
}

/** @internal */
export const OutputMessage$inboundSchema: z.ZodType<
  OutputMessage,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => OutputMessageOutputText$inboundSchema),
  z.lazy(() => OutputMessageRefusal$inboundSchema),
]);
/** @internal */
export type OutputMessage$Outbound =
  | OutputMessageOutputText$Outbound
  | OutputMessageRefusal$Outbound;

/** @internal */
export const OutputMessage$outboundSchema: z.ZodType<
  OutputMessage$Outbound,
  z.ZodTypeDef,
  OutputMessage
> = z.union([
  z.lazy(() => OutputMessageOutputText$outboundSchema),
  z.lazy(() => OutputMessageRefusal$outboundSchema),
]);

export function outputMessageToJSON(outputMessage: OutputMessage): string {
  return JSON.stringify(OutputMessage$outboundSchema.parse(outputMessage));
}
export function outputMessageFromJSON(
  jsonString: string,
): SafeParseResult<OutputMessage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OutputMessage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OutputMessage' from JSON`,
  );
}
