/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import {
  collectExtraKeys as collectExtraKeys$,
  safeParse,
} from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Server-sent event from the streaming Responses API. Contains dynamic fields based on event type (response.created, response.output_text.delta, etc.)
 */
export type ResponseEventData = {
  /**
   * The type of event (e.g., response.created, response.output_text.delta, response.done)
   */
  type: string;
  /**
   * Monotonically increasing sequence number for events in this response
   */
  sequenceNumber: number;
  additionalProperties?: { [k: string]: any } | undefined;
};

export type ResponseEvent = {
  /**
   * Server-sent event from the streaming Responses API. Contains dynamic fields based on event type (response.created, response.output_text.delta, etc.)
   */
  data: ResponseEventData;
};

/** @internal */
export const ResponseEventData$inboundSchema: z.ZodType<
  ResponseEventData,
  z.ZodTypeDef,
  unknown
> = collectExtraKeys$(
  z.object({
    type: z.string(),
    sequence_number: z.number().int(),
  }).catchall(z.any()),
  "additionalProperties",
  true,
).transform((v) => {
  return remap$(v, {
    "sequence_number": "sequenceNumber",
  });
});

export function responseEventDataFromJSON(
  jsonString: string,
): SafeParseResult<ResponseEventData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResponseEventData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResponseEventData' from JSON`,
  );
}

/** @internal */
export const ResponseEvent$inboundSchema: z.ZodType<
  ResponseEvent,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.string().transform((v, ctx) => {
    try {
      return JSON.parse(v);
    } catch (err) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message: `malformed json: ${err}`,
      });
      return z.NEVER;
    }
  }).pipe(z.lazy(() => ResponseEventData$inboundSchema)),
});

export function responseEventFromJSON(
  jsonString: string,
): SafeParseResult<ResponseEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResponseEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResponseEvent' from JSON`,
  );
}
