/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import {
  InputItemUnion,
  InputItemUnion$Outbound,
  InputItemUnion$outboundSchema,
} from "./inputitemunion.js";

export type ResponsesRequestStreamConversation = string | any;

export type ResponsesRequestStreamInput = string | Array<InputItemUnion>;

export type ResponsesRequestStreamToolChoice = string | any;

export type ResponsesRequestStream = {
  background?: boolean | null | undefined;
  conversation?: string | any | null | undefined;
  include?: Array<any> | null | undefined;
  input?: string | Array<InputItemUnion> | null | undefined;
  instructions?: string | null | undefined;
  maxOutputTokens?: number | null | undefined;
  maxToolCalls?: number | null | undefined;
  metadata?: any | undefined;
  model?: string | null | undefined;
  parallelToolCalls?: boolean | null | undefined;
  previousResponseId?: string | null | undefined;
  prompt?: any | undefined;
  promptCacheKey?: string | null | undefined;
  reasoning?: any | undefined;
  safetyIdentifier?: string | null | undefined;
  serviceTier?: string | null | undefined;
  store?: boolean | null | undefined;
  /**
   * If set, partial message deltas and streaming events will be sent. For streaming responses, this must be set to true.
   */
  stream?: boolean | undefined;
  streamOptions?: any | undefined;
  temperature?: number | null | undefined;
  text?: any | undefined;
  toolChoice?: string | any | null | undefined;
  tools?: Array<any> | null | undefined;
  topLogprobs?: number | null | undefined;
  topP?: number | null | undefined;
  truncation?: string | null | undefined;
};

/** @internal */
export type ResponsesRequestStreamConversation$Outbound = string | any;

/** @internal */
export const ResponsesRequestStreamConversation$outboundSchema: z.ZodType<
  ResponsesRequestStreamConversation$Outbound,
  z.ZodTypeDef,
  ResponsesRequestStreamConversation
> = z.union([z.string(), z.any()]);

export function responsesRequestStreamConversationToJSON(
  responsesRequestStreamConversation: ResponsesRequestStreamConversation,
): string {
  return JSON.stringify(
    ResponsesRequestStreamConversation$outboundSchema.parse(
      responsesRequestStreamConversation,
    ),
  );
}

/** @internal */
export type ResponsesRequestStreamInput$Outbound =
  | string
  | Array<InputItemUnion$Outbound>;

/** @internal */
export const ResponsesRequestStreamInput$outboundSchema: z.ZodType<
  ResponsesRequestStreamInput$Outbound,
  z.ZodTypeDef,
  ResponsesRequestStreamInput
> = z.union([z.string(), z.array(InputItemUnion$outboundSchema)]);

export function responsesRequestStreamInputToJSON(
  responsesRequestStreamInput: ResponsesRequestStreamInput,
): string {
  return JSON.stringify(
    ResponsesRequestStreamInput$outboundSchema.parse(
      responsesRequestStreamInput,
    ),
  );
}

/** @internal */
export type ResponsesRequestStreamToolChoice$Outbound = string | any;

/** @internal */
export const ResponsesRequestStreamToolChoice$outboundSchema: z.ZodType<
  ResponsesRequestStreamToolChoice$Outbound,
  z.ZodTypeDef,
  ResponsesRequestStreamToolChoice
> = z.union([z.string(), z.any()]);

export function responsesRequestStreamToolChoiceToJSON(
  responsesRequestStreamToolChoice: ResponsesRequestStreamToolChoice,
): string {
  return JSON.stringify(
    ResponsesRequestStreamToolChoice$outboundSchema.parse(
      responsesRequestStreamToolChoice,
    ),
  );
}

/** @internal */
export type ResponsesRequestStream$Outbound = {
  background?: boolean | null | undefined;
  conversation?: string | any | null | undefined;
  include?: Array<any> | null | undefined;
  input?: string | Array<InputItemUnion$Outbound> | null | undefined;
  instructions?: string | null | undefined;
  max_output_tokens?: number | null | undefined;
  max_tool_calls?: number | null | undefined;
  metadata?: any | undefined;
  model?: string | null | undefined;
  parallel_tool_calls?: boolean | null | undefined;
  previous_response_id?: string | null | undefined;
  prompt?: any | undefined;
  prompt_cache_key?: string | null | undefined;
  reasoning?: any | undefined;
  safety_identifier?: string | null | undefined;
  service_tier?: string | null | undefined;
  store?: boolean | null | undefined;
  stream: boolean;
  stream_options?: any | undefined;
  temperature?: number | null | undefined;
  text?: any | undefined;
  tool_choice?: string | any | null | undefined;
  tools?: Array<any> | null | undefined;
  top_logprobs?: number | null | undefined;
  top_p?: number | null | undefined;
  truncation?: string | null | undefined;
};

/** @internal */
export const ResponsesRequestStream$outboundSchema: z.ZodType<
  ResponsesRequestStream$Outbound,
  z.ZodTypeDef,
  ResponsesRequestStream
> = z.object({
  background: z.nullable(z.boolean()).optional(),
  conversation: z.nullable(z.union([z.string(), z.any()])).optional(),
  include: z.nullable(z.array(z.any())).optional(),
  input: z.nullable(
    z.union([z.string(), z.array(InputItemUnion$outboundSchema)]),
  ).optional(),
  instructions: z.nullable(z.string()).optional(),
  maxOutputTokens: z.nullable(z.number().int()).optional(),
  maxToolCalls: z.nullable(z.number().int()).optional(),
  metadata: z.any().optional(),
  model: z.nullable(z.string()).optional(),
  parallelToolCalls: z.nullable(z.boolean()).optional(),
  previousResponseId: z.nullable(z.string()).optional(),
  prompt: z.any().optional(),
  promptCacheKey: z.nullable(z.string()).optional(),
  reasoning: z.any().optional(),
  safetyIdentifier: z.nullable(z.string()).optional(),
  serviceTier: z.nullable(z.string()).optional(),
  store: z.nullable(z.boolean()).optional(),
  stream: z.boolean().default(true),
  streamOptions: z.any().optional(),
  temperature: z.nullable(z.number()).optional(),
  text: z.any().optional(),
  toolChoice: z.nullable(z.union([z.string(), z.any()])).optional(),
  tools: z.nullable(z.array(z.any())).optional(),
  topLogprobs: z.nullable(z.number().int()).optional(),
  topP: z.nullable(z.number()).optional(),
  truncation: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    maxOutputTokens: "max_output_tokens",
    maxToolCalls: "max_tool_calls",
    parallelToolCalls: "parallel_tool_calls",
    previousResponseId: "previous_response_id",
    promptCacheKey: "prompt_cache_key",
    safetyIdentifier: "safety_identifier",
    serviceTier: "service_tier",
    streamOptions: "stream_options",
    toolChoice: "tool_choice",
    topLogprobs: "top_logprobs",
    topP: "top_p",
  });
});

export function responsesRequestStreamToJSON(
  responsesRequestStream: ResponsesRequestStream,
): string {
  return JSON.stringify(
    ResponsesRequestStream$outboundSchema.parse(responsesRequestStream),
  );
}
