/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  ContentPartUnion,
  ContentPartUnion$inboundSchema,
} from "./contentpartunion.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type ReturnedChatMessages = {
  content?: string | null | undefined;
  contentParts?: Array<ContentPartUnion> | null | undefined;
  id: string;
  name?: string | null | undefined;
  role: string;
};

/** @internal */
export const ReturnedChatMessages$inboundSchema: z.ZodType<
  ReturnedChatMessages,
  z.ZodTypeDef,
  unknown
> = z.object({
  content: z.nullable(z.string()).optional(),
  content_parts: z.nullable(z.array(ContentPartUnion$inboundSchema)).optional(),
  id: z.string(),
  name: z.nullable(z.string()).optional(),
  role: z.string(),
}).transform((v) => {
  return remap$(v, {
    "content_parts": "contentParts",
  });
});

export function returnedChatMessagesFromJSON(
  jsonString: string,
): SafeParseResult<ReturnedChatMessages, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ReturnedChatMessages$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ReturnedChatMessages' from JSON`,
  );
}
