/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  SupportedModel,
  SupportedModel$inboundSchema,
} from "./supportedmodel.js";

export type SupportedModelsList = {
  data: Array<SupportedModel>;
  firstId: string;
  hasMore: boolean;
  lastId: string;
};

/** @internal */
export const SupportedModelsList$inboundSchema: z.ZodType<
  SupportedModelsList,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(SupportedModel$inboundSchema),
  first_id: z.string(),
  has_more: z.boolean(),
  last_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "first_id": "firstId",
    "has_more": "hasMore",
    "last_id": "lastId",
  });
});

export function supportedModelsListFromJSON(
  jsonString: string,
): SafeParseResult<SupportedModelsList, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SupportedModelsList$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SupportedModelsList' from JSON`,
  );
}
