/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type SupportedModel = {
  createdAt: Date;
  modelName: string;
  modelProvider: string;
  sudoModelId: number;
};

/** @internal */
export const SupportedModel$inboundSchema: z.ZodType<
  SupportedModel,
  z.ZodTypeDef,
  unknown
> = z.object({
  created_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  model_name: z.string(),
  model_provider: z.string(),
  sudo_model_id: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    "created_at": "createdAt",
    "model_name": "modelName",
    "model_provider": "modelProvider",
    "sudo_model_id": "sudoModelId",
  });
});

export function supportedModelFromJSON(
  jsonString: string,
): SafeParseResult<SupportedModel, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SupportedModel$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SupportedModel' from JSON`,
  );
}
