/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  FunctionT,
  FunctionT$Outbound,
  FunctionT$outboundSchema,
} from "./function.js";

export type Tool = {
  function: FunctionT;
  type: string;
};

/** @internal */
export type Tool$Outbound = {
  function: FunctionT$Outbound;
  type: string;
};

/** @internal */
export const Tool$outboundSchema: z.ZodType<Tool$Outbound, z.ZodTypeDef, Tool> =
  z.object({
    function: FunctionT$outboundSchema,
    type: z.string(),
  });

export function toolToJSON(tool: Tool): string {
  return JSON.stringify(Tool$outboundSchema.parse(tool));
}
