/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type ToolCallOutput = string | Array<any>;

/** @internal */
export const ToolCallOutput$inboundSchema: z.ZodType<
  ToolCallOutput,
  z.ZodTypeDef,
  unknown
> = z.union([z.string(), z.array(z.any())]);
/** @internal */
export type ToolCallOutput$Outbound = string | Array<any>;

/** @internal */
export const ToolCallOutput$outboundSchema: z.ZodType<
  ToolCallOutput$Outbound,
  z.ZodTypeDef,
  ToolCallOutput
> = z.union([z.string(), z.array(z.any())]);

export function toolCallOutputToJSON(toolCallOutput: ToolCallOutput): string {
  return JSON.stringify(ToolCallOutput$outboundSchema.parse(toolCallOutput));
}
export function toolCallOutputFromJSON(
  jsonString: string,
): SafeParseResult<ToolCallOutput, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ToolCallOutput$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ToolCallOutput' from JSON`,
  );
}
