/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type Usage = {
  completionTokens: number;
  completionTokensDetails?: any | undefined;
  promptTokens: number;
  promptTokensDetails?: any | undefined;
  totalTokens: number;
};

/** @internal */
export const Usage$inboundSchema: z.ZodType<Usage, z.ZodTypeDef, unknown> = z
  .object({
    completion_tokens: z.number().int(),
    completion_tokens_details: z.any().optional(),
    prompt_tokens: z.number().int(),
    prompt_tokens_details: z.any().optional(),
    total_tokens: z.number().int(),
  }).transform((v) => {
    return remap$(v, {
      "completion_tokens": "completionTokens",
      "completion_tokens_details": "completionTokensDetails",
      "prompt_tokens": "promptTokens",
      "prompt_tokens_details": "promptTokensDetails",
      "total_tokens": "totalTokens",
    });
  });

export function usageFromJSON(
  jsonString: string,
): SafeParseResult<Usage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Usage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Usage' from JSON`,
  );
}
